// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/continuous-labs-ai/cli/internal/sdk/models/components"
	"github.com/continuous-labs-ai/cli/internal/sdk/sdkinternal/utils"
)

type AdvanceWorldTimeRequest struct {
	// Simulation or World ID.
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// Stable key for this request. Reuse with the same target returns the same operation.
	IdempotencyKey string                          `header:"style=simple,explode=false,name=Idempotency-Key"`
	Body           components.AdvanceTimeInputBody `request:"mediaType=application/json"`
}

func (a *AdvanceWorldTimeRequest) GetID() string {
	if a == nil {
		return ""
	}
	return a.ID
}

func (a *AdvanceWorldTimeRequest) GetIdempotencyKey() string {
	if a == nil {
		return ""
	}
	return a.IdempotencyKey
}

func (a *AdvanceWorldTimeRequest) GetBody() components.AdvanceTimeInputBody {
	if a == nil {
		return components.AdvanceTimeInputBody{}
	}
	return a.Body
}

type AdvanceWorldTimeResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Accepted
	ClockAdvance *components.ClockAdvance
}

func (a AdvanceWorldTimeResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AdvanceWorldTimeResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AdvanceWorldTimeResponse) GetHTTPMeta() components.HTTPMetadata {
	if a == nil {
		return components.HTTPMetadata{}
	}
	return a.HTTPMeta
}

func (a *AdvanceWorldTimeResponse) GetClockAdvance() *components.ClockAdvance {
	if a == nil {
		return nil
	}
	return a.ClockAdvance
}
