// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/continuous-labs-ai/continuous-simulation-cli/internal/sdk/models/components"
	"github.com/continuous-labs-ai/continuous-simulation-cli/internal/sdk/sdkinternal/utils"
)

type Spec struct {
	FileName string `multipartForm:"name=fileName"`
	Content  []byte `multipartForm:"content"`
}

func (s *Spec) GetFileName() string {
	if s == nil {
		return ""
	}
	return s.FileName
}

func (s *Spec) GetContent() []byte {
	if s == nil {
		return []byte{}
	}
	return s.Content
}

type BuildSimulatorRequest struct {
	Request components.BuildSimulatorRequest `multipartForm:"name=request,json"`
	// OpenAPI or WSDL file. A spec build sends it. At most 67,108,864 UTF-8 bytes.
	Spec *Spec `multipartForm:"file,name=spec"`
}

func (b BuildSimulatorRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(b, "", false)
}

func (b *BuildSimulatorRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &b, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (b *BuildSimulatorRequest) GetRequest() components.BuildSimulatorRequest {
	if b == nil {
		return components.BuildSimulatorRequest{}
	}
	return b.Request
}

func (b *BuildSimulatorRequest) GetSpec() *Spec {
	if b == nil {
		return nil
	}
	return b.Spec
}

type BuildSimulatorResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Accepted
	Simulator *components.Simulator
}

func (b BuildSimulatorResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(b, "", false)
}

func (b *BuildSimulatorResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &b, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (b *BuildSimulatorResponse) GetHTTPMeta() components.HTTPMetadata {
	if b == nil {
		return components.HTTPMetadata{}
	}
	return b.HTTPMeta
}

func (b *BuildSimulatorResponse) GetSimulator() *components.Simulator {
	if b == nil {
		return nil
	}
	return b.Simulator
}
