// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/continuous-labs-ai/cli/internal/sdk/models/components"
	"github.com/continuous-labs-ai/cli/internal/sdk/sdkinternal/utils"
)

type Document struct {
	FileName string `multipartForm:"name=fileName"`
	Content  []byte `multipartForm:"content"`
}

func (d *Document) GetFileName() string {
	if d == nil {
		return ""
	}
	return d.FileName
}

func (d *Document) GetContent() []byte {
	if d == nil {
		return []byte{}
	}
	return d.Content
}

type Spec struct {
	FileName string `multipartForm:"name=fileName"`
	Content  []byte `multipartForm:"content"`
}

func (s *Spec) GetFileName() string {
	if s == nil {
		return ""
	}
	return s.FileName
}

func (s *Spec) GetContent() []byte {
	if s == nil {
		return []byte{}
	}
	return s.Content
}

type BuildSimulatorRequest struct {
	// Vendor documentation the builder and reviewer read before they start, as repeated file parts: UTF-8 text (.md, .txt, .html, .json, .yaml, .xml, .csv) or PDF (.pdf). The documents share the request body limit with the spec. A parent's documents are not inherited.
	Document []Document                       `multipartForm:"file,name=document"`
	Request  components.BuildSimulatorRequest `multipartForm:"name=request,json"`
	// OpenAPI or WSDL document, UTF-8 encoded, at most 64 MiB. Required unless the request is an incremental build (parent_id and instructions, no spec).
	Spec *Spec `multipartForm:"file,name=spec"`
}

func (b BuildSimulatorRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(b, "", false)
}

func (b *BuildSimulatorRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &b, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (b *BuildSimulatorRequest) GetDocument() []Document {
	if b == nil {
		return nil
	}
	return b.Document
}

func (b *BuildSimulatorRequest) GetRequest() components.BuildSimulatorRequest {
	if b == nil {
		return components.BuildSimulatorRequest{}
	}
	return b.Request
}

func (b *BuildSimulatorRequest) GetSpec() *Spec {
	if b == nil {
		return nil
	}
	return b.Spec
}

type BuildSimulatorResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Accepted
	Simulator *components.Simulator
	Headers   map[string][]string
}

func (b BuildSimulatorResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(b, "", false)
}

func (b *BuildSimulatorResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &b, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (b *BuildSimulatorResponse) GetHTTPMeta() components.HTTPMetadata {
	if b == nil {
		return components.HTTPMetadata{}
	}
	return b.HTTPMeta
}

func (b *BuildSimulatorResponse) GetSimulator() *components.Simulator {
	if b == nil {
		return nil
	}
	return b.Simulator
}

func (b *BuildSimulatorResponse) GetHeaders() map[string][]string {
	if b == nil {
		return map[string][]string{}
	}
	return b.Headers
}
