// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/continuous-labs-ai/cli/internal/sdk/models/components"
	"github.com/continuous-labs-ai/cli/internal/sdk/sdkinternal/utils"
)

type CancelSimulatorBuildRequest struct {
	// Stable Simulator ID.
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (c *CancelSimulatorBuildRequest) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}

type CancelSimulatorBuildResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	Simulator *components.Simulator
}

func (c CancelSimulatorBuildResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CancelSimulatorBuildResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CancelSimulatorBuildResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CancelSimulatorBuildResponse) GetSimulator() *components.Simulator {
	if c == nil {
		return nil
	}
	return c.Simulator
}
