// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/continuous-labs-ai/cli/internal/sdk/models/components"
	"github.com/continuous-labs-ai/cli/internal/sdk/sdkinternal/utils"
)

type CancelWorldRequest struct {
	// World ID.
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (c *CancelWorldRequest) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}

type CancelWorldResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	World *components.World
}

func (c CancelWorldResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CancelWorldResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CancelWorldResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CancelWorldResponse) GetWorld() *components.World {
	if c == nil {
		return nil
	}
	return c.World
}
