// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/continuous-labs-ai/cli/internal/sdk/models/components"
)

type DeleteCredentialRequest struct {
	// Credential ID.
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (d *DeleteCredentialRequest) GetID() string {
	if d == nil {
		return ""
	}
	return d.ID
}

type DeleteCredentialResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (d *DeleteCredentialResponse) GetHTTPMeta() components.HTTPMetadata {
	if d == nil {
		return components.HTTPMetadata{}
	}
	return d.HTTPMeta
}
