// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/continuous-labs-ai/continuous-simulation-cli/internal/sdk/models/components"
)

type DeleteSimulationRequest struct {
	// Stable resource ID.
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (d *DeleteSimulationRequest) GetID() string {
	if d == nil {
		return ""
	}
	return d.ID
}

type DeleteSimulationResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (d *DeleteSimulationResponse) GetHTTPMeta() components.HTTPMetadata {
	if d == nil {
		return components.HTTPMetadata{}
	}
	return d.HTTPMeta
}
