// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/continuous-labs-ai/continuous-simulation-cli/internal/sdk/models/components"
	"github.com/continuous-labs-ai/continuous-simulation-cli/internal/sdk/sdkinternal/utils"
)

type ForkSimulationRequest struct {
	// Stable source Simulation ID.
	ID   string                           `pathParam:"style=simple,explode=false,name=id"`
	Body components.ForkSimulationRequest `request:"mediaType=application/json"`
}

func (f *ForkSimulationRequest) GetID() string {
	if f == nil {
		return ""
	}
	return f.ID
}

func (f *ForkSimulationRequest) GetBody() components.ForkSimulationRequest {
	if f == nil {
		return components.ForkSimulationRequest{}
	}
	return f.Body
}

type ForkSimulationResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Created
	CreatedSimulation *components.CreatedSimulation
}

func (f ForkSimulationResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(f, "", false)
}

func (f *ForkSimulationResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &f, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (f *ForkSimulationResponse) GetHTTPMeta() components.HTTPMetadata {
	if f == nil {
		return components.HTTPMetadata{}
	}
	return f.HTTPMeta
}

func (f *ForkSimulationResponse) GetCreatedSimulation() *components.CreatedSimulation {
	if f == nil {
		return nil
	}
	return f.CreatedSimulation
}
