// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/continuous-labs-ai/cli/internal/sdk/models/components"
	"github.com/continuous-labs-ai/cli/internal/sdk/sdkinternal/utils"
)

type GetCredentialRequest struct {
	// Credential ID.
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (g *GetCredentialRequest) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

type GetCredentialResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	Credential *components.Credential
}

func (g GetCredentialResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetCredentialResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetCredentialResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetCredentialResponse) GetCredential() *components.Credential {
	if g == nil {
		return nil
	}
	return g.Credential
}
