// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/continuous-labs-ai/cli/internal/sdk/models/components"
	"github.com/continuous-labs-ai/cli/internal/sdk/sdkinternal/utils"
)

type GetSimulationTokenRequest struct {
	// Simulation ID.
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (g *GetSimulationTokenRequest) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

type GetSimulationTokenResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	CurrentSimulationToken *components.CurrentSimulationToken
	Headers                map[string][]string
}

func (g GetSimulationTokenResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetSimulationTokenResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetSimulationTokenResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetSimulationTokenResponse) GetCurrentSimulationToken() *components.CurrentSimulationToken {
	if g == nil {
		return nil
	}
	return g.CurrentSimulationToken
}

func (g *GetSimulationTokenResponse) GetHeaders() map[string][]string {
	if g == nil {
		return map[string][]string{}
	}
	return g.Headers
}
