// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/continuous-labs-ai/cli/internal/sdk/models/components"
	"github.com/continuous-labs-ai/cli/internal/sdk/sdkinternal/utils"
)

type GetSimulationAdvanceRequest struct {
	// Simulation or World ID.
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// Clock advance operation ID.
	AdvanceID string `pathParam:"style=simple,explode=false,name=advance_id"`
}

func (g *GetSimulationAdvanceRequest) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

func (g *GetSimulationAdvanceRequest) GetAdvanceID() string {
	if g == nil {
		return ""
	}
	return g.AdvanceID
}

type GetSimulationAdvanceResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	ClockAdvance *components.ClockAdvance
}

func (g GetSimulationAdvanceResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetSimulationAdvanceResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetSimulationAdvanceResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetSimulationAdvanceResponse) GetClockAdvance() *components.ClockAdvance {
	if g == nil {
		return nil
	}
	return g.ClockAdvance
}
