// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/continuous-labs-ai/cli/internal/sdk/models/components"
	"github.com/continuous-labs-ai/cli/internal/sdk/sdkinternal/utils"
)

type GetSimulationRequest struct {
	// Simulation ID.
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (g *GetSimulationRequest) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

type GetSimulationResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	Simulation *components.Simulation
}

func (g GetSimulationResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetSimulationResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetSimulationResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetSimulationResponse) GetSimulation() *components.Simulation {
	if g == nil {
		return nil
	}
	return g.Simulation
}
