// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/continuous-labs-ai/cli/internal/sdk/models/components"
	"github.com/continuous-labs-ai/cli/internal/sdk/sdkinternal/utils"
)

type GetWorldRequest struct {
	// Stable World ID.
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (g *GetWorldRequest) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

type GetWorldResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	World *components.World
}

func (g GetWorldResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetWorldResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetWorldResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetWorldResponse) GetWorld() *components.World {
	if g == nil {
		return nil
	}
	return g.World
}
