// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/continuous-labs-ai/cli/internal/sdk/models/components"
	"github.com/continuous-labs-ai/cli/internal/sdk/sdkinternal/utils"
)

type ListSimulationAdvanceEventsRequest struct {
	// Simulation ID.
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// Advance ID. A historical fork can read inherited runtime receipts.
	AdvanceID string `pathParam:"style=simple,explode=false,name=advance_id"`
	// Cursor from the previous page.
	Cursor *string `queryParam:"style=form,explode=false,name=cursor"`
	// Page size, up to 200.
	Limit *int64 `default:"50" queryParam:"style=form,explode=false,name=limit"`
}

func (l ListSimulationAdvanceEventsRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListSimulationAdvanceEventsRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListSimulationAdvanceEventsRequest) GetID() string {
	if l == nil {
		return ""
	}
	return l.ID
}

func (l *ListSimulationAdvanceEventsRequest) GetAdvanceID() string {
	if l == nil {
		return ""
	}
	return l.AdvanceID
}

func (l *ListSimulationAdvanceEventsRequest) GetCursor() *string {
	if l == nil {
		return nil
	}
	return l.Cursor
}

func (l *ListSimulationAdvanceEventsRequest) GetLimit() *int64 {
	if l == nil {
		return nil
	}
	return l.Limit
}

type ListSimulationAdvanceEventsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	ListAdvanceEventsOutputBody *components.ListAdvanceEventsOutputBody
}

func (l ListSimulationAdvanceEventsResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListSimulationAdvanceEventsResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListSimulationAdvanceEventsResponse) GetHTTPMeta() components.HTTPMetadata {
	if l == nil {
		return components.HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *ListSimulationAdvanceEventsResponse) GetListAdvanceEventsOutputBody() *components.ListAdvanceEventsOutputBody {
	if l == nil {
		return nil
	}
	return l.ListAdvanceEventsOutputBody
}
