// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/continuous-labs-ai/continuous-simulation-cli/internal/sdk/models/components"
	"github.com/continuous-labs-ai/continuous-simulation-cli/internal/sdk/sdkinternal/utils"
)

// ListSimulationsStatus - Optional lifecycle status filter.
type ListSimulationsStatus string

const (
	ListSimulationsStatusRunning ListSimulationsStatus = "running"
	ListSimulationsStatusPaused  ListSimulationsStatus = "paused"
	ListSimulationsStatusStopped ListSimulationsStatus = "stopped"
)

func (e ListSimulationsStatus) ToPointer() *ListSimulationsStatus {
	return &e
}
func (e *ListSimulationsStatus) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "running":
		fallthrough
	case "paused":
		fallthrough
	case "stopped":
		*e = ListSimulationsStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ListSimulationsStatus: %v", v)
	}
}

type ListSimulationsRequest struct {
	// Optional lifecycle status filter.
	Status *ListSimulationsStatus `queryParam:"style=form,explode=false,name=status"`
	// Optional stable Simulator ID filter.
	SimulatorID *string `queryParam:"style=form,explode=false,name=simulator_id"`
	// Page size. Values below 1 use 50. Values above 200 use 200.
	Limit *int64 `default:"50" queryParam:"style=form,explode=false,name=limit"`
	// Opaque next_cursor value from a previous page.
	Cursor *string `queryParam:"style=form,explode=false,name=cursor"`
}

func (l ListSimulationsRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListSimulationsRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListSimulationsRequest) GetStatus() *ListSimulationsStatus {
	if l == nil {
		return nil
	}
	return l.Status
}

func (l *ListSimulationsRequest) GetSimulatorID() *string {
	if l == nil {
		return nil
	}
	return l.SimulatorID
}

func (l *ListSimulationsRequest) GetLimit() *int64 {
	if l == nil {
		return nil
	}
	return l.Limit
}

func (l *ListSimulationsRequest) GetCursor() *string {
	if l == nil {
		return nil
	}
	return l.Cursor
}

type ListSimulationsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	ListSimulationsResponse *components.ListSimulationsResponse
}

func (l ListSimulationsResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListSimulationsResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListSimulationsResponse) GetHTTPMeta() components.HTTPMetadata {
	if l == nil {
		return components.HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *ListSimulationsResponse) GetListSimulationsResponse() *components.ListSimulationsResponse {
	if l == nil {
		return nil
	}
	return l.ListSimulationsResponse
}
