// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/continuous-labs-ai/continuous-simulation-cli/internal/sdk/models/components"
	"github.com/continuous-labs-ai/continuous-simulation-cli/internal/sdk/sdkinternal/utils"
)

// ListSimulatorsStatus - Optional build status filter.
type ListSimulatorsStatus string

const (
	ListSimulatorsStatusBuilding ListSimulatorsStatus = "building"
	ListSimulatorsStatusReady    ListSimulatorsStatus = "ready"
	ListSimulatorsStatusFailed   ListSimulatorsStatus = "failed"
	ListSimulatorsStatusCanceled ListSimulatorsStatus = "canceled"
)

func (e ListSimulatorsStatus) ToPointer() *ListSimulatorsStatus {
	return &e
}
func (e *ListSimulatorsStatus) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "building":
		fallthrough
	case "ready":
		fallthrough
	case "failed":
		fallthrough
	case "canceled":
		*e = ListSimulatorsStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ListSimulatorsStatus: %v", v)
	}
}

type ListSimulatorsRequest struct {
	// Optional build status filter.
	Status *ListSimulatorsStatus `queryParam:"style=form,explode=false,name=status"`
	// Optional exact Simulator name. Prefix a catalog name with continuous/. Names cannot start with smr_.
	Name *string `queryParam:"style=form,explode=false,name=name"`
	// Page size. Values below 1 use 50. Values above 200 use 200.
	Limit *int64 `default:"50" queryParam:"style=form,explode=false,name=limit"`
	// Opaque next_cursor value from a previous page.
	Cursor *string `queryParam:"style=form,explode=false,name=cursor"`
}

func (l ListSimulatorsRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListSimulatorsRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListSimulatorsRequest) GetStatus() *ListSimulatorsStatus {
	if l == nil {
		return nil
	}
	return l.Status
}

func (l *ListSimulatorsRequest) GetName() *string {
	if l == nil {
		return nil
	}
	return l.Name
}

func (l *ListSimulatorsRequest) GetLimit() *int64 {
	if l == nil {
		return nil
	}
	return l.Limit
}

func (l *ListSimulatorsRequest) GetCursor() *string {
	if l == nil {
		return nil
	}
	return l.Cursor
}

type ListSimulatorsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	ListSimulatorsResponse *components.ListSimulatorsResponse
}

func (l ListSimulatorsResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListSimulatorsResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListSimulatorsResponse) GetHTTPMeta() components.HTTPMetadata {
	if l == nil {
		return components.HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *ListSimulatorsResponse) GetListSimulatorsResponse() *components.ListSimulatorsResponse {
	if l == nil {
		return nil
	}
	return l.ListSimulatorsResponse
}
