// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/continuous-labs-ai/continuous-simulation-cli/internal/sdk/models/components"
	"github.com/continuous-labs-ai/continuous-simulation-cli/internal/sdk/sdkinternal/utils"
)

type ListSimulationStepsRequest struct {
	// Stable Simulation ID.
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// Opaque next_cursor value from a previous page.
	Cursor *string `queryParam:"style=form,explode=false,name=cursor"`
	// Page size. Values below 1 use 50. Values above 200 use 200.
	Limit *int64 `default:"50" queryParam:"style=form,explode=false,name=limit"`
}

func (l ListSimulationStepsRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListSimulationStepsRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListSimulationStepsRequest) GetID() string {
	if l == nil {
		return ""
	}
	return l.ID
}

func (l *ListSimulationStepsRequest) GetCursor() *string {
	if l == nil {
		return nil
	}
	return l.Cursor
}

func (l *ListSimulationStepsRequest) GetLimit() *int64 {
	if l == nil {
		return nil
	}
	return l.Limit
}

type ListSimulationStepsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	ListSimulationStepsResponse *components.ListSimulationStepsResponse
}

func (l ListSimulationStepsResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListSimulationStepsResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListSimulationStepsResponse) GetHTTPMeta() components.HTTPMetadata {
	if l == nil {
		return components.HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *ListSimulationStepsResponse) GetListSimulationStepsResponse() *components.ListSimulationStepsResponse {
	if l == nil {
		return nil
	}
	return l.ListSimulationStepsResponse
}
