// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/continuous-labs-ai/cli/internal/sdk/models/components"
	"github.com/continuous-labs-ai/cli/internal/sdk/sdkinternal/utils"
)

type ListCredentialsRequest struct {
	// Page size. Values below 1 use 50. Values above 200 use 200.
	Limit *int64 `default:"50" queryParam:"style=form,explode=false,name=limit"`
	// Opaque next_cursor value from a previous page.
	Cursor *string `queryParam:"style=form,explode=false,name=cursor"`
}

func (l ListCredentialsRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListCredentialsRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListCredentialsRequest) GetLimit() *int64 {
	if l == nil {
		return nil
	}
	return l.Limit
}

func (l *ListCredentialsRequest) GetCursor() *string {
	if l == nil {
		return nil
	}
	return l.Cursor
}

type ListCredentialsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	ListCredentialsResponse *components.ListCredentialsResponse
}

func (l ListCredentialsResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListCredentialsResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListCredentialsResponse) GetHTTPMeta() components.HTTPMetadata {
	if l == nil {
		return components.HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *ListCredentialsResponse) GetListCredentialsResponse() *components.ListCredentialsResponse {
	if l == nil {
		return nil
	}
	return l.ListCredentialsResponse
}
