// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/continuous-labs-ai/cli/internal/sdk/models/components"
	"github.com/continuous-labs-ai/cli/internal/sdk/sdkinternal/utils"
)

type MintSimulationTokenRequest struct {
	// Stable Simulation ID.
	ID   string                                `pathParam:"style=simple,explode=false,name=id"`
	Body components.MintSimulationTokenRequest `request:"mediaType=application/json"`
}

func (m *MintSimulationTokenRequest) GetID() string {
	if m == nil {
		return ""
	}
	return m.ID
}

func (m *MintSimulationTokenRequest) GetBody() components.MintSimulationTokenRequest {
	if m == nil {
		return components.MintSimulationTokenRequest{}
	}
	return m.Body
}

type MintSimulationTokenResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	SimulationToken *components.SimulationToken
}

func (m MintSimulationTokenResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(m, "", false)
}

func (m *MintSimulationTokenResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &m, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (m *MintSimulationTokenResponse) GetHTTPMeta() components.HTTPMetadata {
	if m == nil {
		return components.HTTPMetadata{}
	}
	return m.HTTPMeta
}

func (m *MintSimulationTokenResponse) GetSimulationToken() *components.SimulationToken {
	if m == nil {
		return nil
	}
	return m.SimulationToken
}
