// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/continuous-labs-ai/cli/internal/sdk/models/components"
	"github.com/continuous-labs-ai/cli/internal/sdk/sdkinternal/utils"
)

type RegenerateSimulationTokenRequest struct {
	// Simulation ID.
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// Stable key for this regeneration request.
	IdempotencyKey string `header:"style=simple,explode=false,name=Idempotency-Key"`
}

func (r *RegenerateSimulationTokenRequest) GetID() string {
	if r == nil {
		return ""
	}
	return r.ID
}

func (r *RegenerateSimulationTokenRequest) GetIdempotencyKey() string {
	if r == nil {
		return ""
	}
	return r.IdempotencyKey
}

type RegenerateSimulationTokenResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	CurrentSimulationToken *components.CurrentSimulationToken
	Headers                map[string][]string
}

func (r RegenerateSimulationTokenResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *RegenerateSimulationTokenResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (r *RegenerateSimulationTokenResponse) GetHTTPMeta() components.HTTPMetadata {
	if r == nil {
		return components.HTTPMetadata{}
	}
	return r.HTTPMeta
}

func (r *RegenerateSimulationTokenResponse) GetCurrentSimulationToken() *components.CurrentSimulationToken {
	if r == nil {
		return nil
	}
	return r.CurrentSimulationToken
}

func (r *RegenerateSimulationTokenResponse) GetHeaders() map[string][]string {
	if r == nil {
		return map[string][]string{}
	}
	return r.Headers
}
