// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/continuous-labs-ai/continuous-simulation-cli/internal/sdk/models/components"
	"github.com/continuous-labs-ai/continuous-simulation-cli/internal/sdk/sdkinternal/utils"
)

type StartSimulationRequest struct {
	// Stable Simulation ID.
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (s *StartSimulationRequest) GetID() string {
	if s == nil {
		return ""
	}
	return s.ID
}

type StartSimulationResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	Simulation *components.Simulation
}

func (s StartSimulationResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *StartSimulationResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *StartSimulationResponse) GetHTTPMeta() components.HTTPMetadata {
	if s == nil {
		return components.HTTPMetadata{}
	}
	return s.HTTPMeta
}

func (s *StartSimulationResponse) GetSimulation() *components.Simulation {
	if s == nil {
		return nil
	}
	return s.Simulation
}
