// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/continuous-labs-ai/cli/internal/sdk/models/components"
	"github.com/continuous-labs-ai/cli/internal/sdk/sdkinternal/utils"
)

type StartWorldRequest struct {
	// World ID.
	ID   string                        `pathParam:"style=simple,explode=false,name=id"`
	Body *components.StartWorldRequest `request:"mediaType=application/json"`
}

func (s StartWorldRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *StartWorldRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *StartWorldRequest) GetID() string {
	if s == nil {
		return ""
	}
	return s.ID
}

func (s *StartWorldRequest) GetBody() *components.StartWorldRequest {
	if s == nil {
		return nil
	}
	return s.Body
}

type StartWorldResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	World *components.World
}

func (s StartWorldResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *StartWorldResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *StartWorldResponse) GetHTTPMeta() components.HTTPMetadata {
	if s == nil {
		return components.HTTPMetadata{}
	}
	return s.HTTPMeta
}

func (s *StartWorldResponse) GetWorld() *components.World {
	if s == nil {
		return nil
	}
	return s.World
}
