// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/continuous-labs-ai/cli/internal/sdk/models/components"
	"github.com/continuous-labs-ai/cli/internal/sdk/sdkinternal/utils"
)

type StopWorldRequest struct {
	// World ID.
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (s *StopWorldRequest) GetID() string {
	if s == nil {
		return ""
	}
	return s.ID
}

type StopWorldResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	World *components.World
}

func (s StopWorldResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *StopWorldResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *StopWorldResponse) GetHTTPMeta() components.HTTPMetadata {
	if s == nil {
		return components.HTTPMetadata{}
	}
	return s.HTTPMeta
}

func (s *StopWorldResponse) GetWorld() *components.World {
	if s == nil {
		return nil
	}
	return s.World
}
