// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/continuous-labs-ai/cli/internal/sdk/models/components"
	"github.com/continuous-labs-ai/cli/internal/sdk/sdkinternal/utils"
)

type UpdateCredentialRequest struct {
	// Credential ID.
	ID   string                             `pathParam:"style=simple,explode=false,name=id"`
	Body components.UpdateCredentialRequest `request:"mediaType=application/json"`
}

func (u *UpdateCredentialRequest) GetID() string {
	if u == nil {
		return ""
	}
	return u.ID
}

func (u *UpdateCredentialRequest) GetBody() components.UpdateCredentialRequest {
	if u == nil {
		return components.UpdateCredentialRequest{}
	}
	return u.Body
}

type UpdateCredentialResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	Credential *components.Credential
}

func (u UpdateCredentialResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateCredentialResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UpdateCredentialResponse) GetHTTPMeta() components.HTTPMetadata {
	if u == nil {
		return components.HTTPMetadata{}
	}
	return u.HTTPMeta
}

func (u *UpdateCredentialResponse) GetCredential() *components.Credential {
	if u == nil {
		return nil
	}
	return u.Credential
}
