// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"github.com/continuous-labs-ai/continuous-simulation-cli/internal/sdk/models/components"
)

type Error struct {
	// Stable machine-readable error code.
	Code string `json:"code"`
	// Safe human-readable error detail.
	Detail   string                  `json:"detail"`
	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &Error{}

func (e *Error) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
