// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package simulations

import (
	"fmt"
	"github.com/continuous-labs-ai/cli/internal/client"
	"github.com/continuous-labs-ai/cli/internal/flagutil"
	"github.com/continuous-labs-ai/cli/internal/interactive"
	"github.com/continuous-labs-ai/cli/internal/output"
	"github.com/continuous-labs-ai/cli/internal/sdk"
	"github.com/continuous-labs-ai/cli/internal/sdk/models/operations"
	"github.com/continuous-labs-ai/cli/internal/usage"
	"github.com/spf13/cobra"
)

var advanceSimulationTimeCmdMeta = []flagutil.FlagMeta{
	{FlagName: "id", FieldPath: "ID", Kind: flagutil.FlagKindString, Required: true, Description: "Simulation or World ID. [required]"},
	{FlagName: "idempotency-key", FieldPath: "IdempotencyKey", Kind: flagutil.FlagKindString, Required: true, Description: "Stable key for this request. Reuse with the same target returns the same operation. [required]"},
	{FlagName: "to", Shorthand: "t", FieldPath: "Body.To", Kind: flagutil.FlagKindDateTime, Required: true, Description: "Absolute target time in RFC 3339, with at most millisecond precision. [required]"},
}

// initAdvanceSimulationTimeCmd initializes the advance-simulation-time command.
func initAdvanceSimulationTimeCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "advance-simulation-time",
		Short:   "Advance Simulation Time",
		Long:    "Schedules an absolute clock advance. Each successful advance commits all due local events in one step. World members advance through their World. Poll the returned operation until it completes.",
		Example: "  continuous simulations advance-simulation-time --id <id> --idempotency-key <value> --to 2026-11-25T01:01:24.107Z",
		RunE:    runAdvanceSimulationTimeCmd,
		Aliases: []string{"ast"},
	}
	flagutil.RegisterFlags(cmd, advanceSimulationTimeCmdMeta)
	if err := flagutil.ValidateMeta[operations.AdvanceSimulationTimeRequest](advanceSimulationTimeCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for advance-simulation-time: %w", err)
	}
	cmd.Flags().String("body", "", "Request body as JSON (alternative to individual flags). Can also be provided via stdin.")
	parent.AddCommand(cmd)
	return nil
}

// runAdvanceSimulationTimeCmd executes the advance-simulation-time command.
func runAdvanceSimulationTimeCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, advanceSimulationTimeCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, advanceSimulationTimeCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.AdvanceSimulationTimeRequest](cmd, advanceSimulationTimeCmdMeta, "Body", "body")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Simulations.AdvanceSimulationTime(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
