// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package simulations

import (
	"fmt"
	"github.com/continuous-labs-ai/cli/internal/client"
	"github.com/continuous-labs-ai/cli/internal/flagutil"
	"github.com/continuous-labs-ai/cli/internal/interactive"
	"github.com/continuous-labs-ai/cli/internal/output"
	"github.com/continuous-labs-ai/cli/internal/sdk"
	"github.com/continuous-labs-ai/cli/internal/sdk/models/operations"
	"github.com/continuous-labs-ai/cli/internal/usage"
	"github.com/spf13/cobra"
)

var deleteSimulationCmdMeta = []flagutil.FlagMeta{
	{FlagName: "id", Shorthand: "i", FieldPath: "ID", Kind: flagutil.FlagKindString, Required: true, Description: "Stable resource ID. [required]"},
}

// initDeleteSimulationCmd initializes the delete-simulation command.
func initDeleteSimulationCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "delete",
		Short:   "Delete Simulation",
		Long:    "Deletes a Simulation and its saved runtime state. Delete World-owned Simulations through their World.",
		Example: "  continuous simulations delete --id <id>",
		RunE:    runDeleteSimulationCmd,
	}
	flagutil.RegisterFlags(cmd, deleteSimulationCmdMeta)
	if err := flagutil.ValidateMeta[operations.DeleteSimulationRequest](deleteSimulationCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for delete-simulation: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runDeleteSimulationCmd executes the delete-simulation command.
func runDeleteSimulationCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, deleteSimulationCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, deleteSimulationCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.DeleteSimulationRequest](cmd, deleteSimulationCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Simulations.DeleteSimulation(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
