// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package simulations

import (
	"fmt"
	"github.com/continuous-labs-ai/cli/internal/client"
	"github.com/continuous-labs-ai/cli/internal/flagutil"
	"github.com/continuous-labs-ai/cli/internal/interactive"
	"github.com/continuous-labs-ai/cli/internal/output"
	"github.com/continuous-labs-ai/cli/internal/sdk"
	"github.com/continuous-labs-ai/cli/internal/sdk/models/operations"
	"github.com/continuous-labs-ai/cli/internal/usage"
	"github.com/spf13/cobra"
)

var forkSimulationCmdMeta = []flagutil.FlagMeta{
	{FlagName: "id", Shorthand: "i", FieldPath: "ID", Kind: flagutil.FlagKindString, Required: true, Description: "Stable source Simulation ID. [required]"},
	{FlagName: "at-step", Shorthand: "a", FieldPath: "Body.AtStep", Kind: flagutil.FlagKindInt64, Optional: true, Description: "Completed step to fork from. Omission forks from the latest state."},
	{FlagName: "name", Shorthand: "n", FieldPath: "Body.Name", Kind: flagutil.FlagKindString, Optional: true, Description: "Optional child Simulation name. Omission generates a name."},
}

// initForkSimulationCmd initializes the fork-simulation command.
func initForkSimulationCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "fork",
		Short:   "Fork Simulation",
		Long:    "Creates a Simulation with a 1-hour token. The source Simulation continues to run.",
		Example: "  continuous simulations fork --id <id>",
		RunE:    runForkSimulationCmd,
	}
	flagutil.RegisterFlags(cmd, forkSimulationCmdMeta)
	if err := flagutil.ValidateMeta[operations.ForkSimulationRequest](forkSimulationCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for fork-simulation: %w", err)
	}
	cmd.Flags().String("body", "", "Request body as JSON (alternative to individual flags). Can also be provided via stdin.")
	parent.AddCommand(cmd)
	return nil
}

// runForkSimulationCmd executes the fork-simulation command.
func runForkSimulationCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, forkSimulationCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, forkSimulationCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.ForkSimulationRequest](cmd, forkSimulationCmdMeta, "Body", "body")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Simulations.ForkSimulation(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
