// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package simulations

import (
	"fmt"
	"github.com/continuous-labs-ai/cli/internal/client"
	"github.com/continuous-labs-ai/cli/internal/flagutil"
	"github.com/continuous-labs-ai/cli/internal/interactive"
	"github.com/continuous-labs-ai/cli/internal/output"
	"github.com/continuous-labs-ai/cli/internal/sdk"
	"github.com/continuous-labs-ai/cli/internal/sdk/models/operations"
	"github.com/continuous-labs-ai/cli/internal/usage"
	"github.com/spf13/cobra"
)

var getSimulationTokenCmdMeta = []flagutil.FlagMeta{
	{FlagName: "id", Shorthand: "i", FieldPath: "ID", Kind: flagutil.FlagKindString, Required: true, Description: "Simulation ID. [required]"},
}

// initGetSimulationTokenCmd initializes the get-simulation-token command.
func initGetSimulationTokenCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "get-simulation-token",
		Short:   "Get Current Simulation Token",
		Long:    "Returns the current persistent credential, including while stopped, without rotating it. Legacy Simulations require the deprecated token-mint endpoint or explicit regeneration.",
		Example: "  continuous simulations get-simulation-token --id <id>",
		RunE:    runGetSimulationTokenCmd,
		Aliases: []string{"gst"},
	}
	flagutil.RegisterFlags(cmd, getSimulationTokenCmdMeta)
	if err := flagutil.ValidateMeta[operations.GetSimulationTokenRequest](getSimulationTokenCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for get-simulation-token: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runGetSimulationTokenCmd executes the get-simulation-token command.
func runGetSimulationTokenCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, getSimulationTokenCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, getSimulationTokenCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.GetSimulationTokenRequest](cmd, getSimulationTokenCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Simulations.GetSimulationToken(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
