// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package simulations

import (
	"fmt"
	"github.com/continuous-labs-ai/continuous-simulation-cli/internal/client"
	"github.com/continuous-labs-ai/continuous-simulation-cli/internal/flagutil"
	"github.com/continuous-labs-ai/continuous-simulation-cli/internal/interactive"
	"github.com/continuous-labs-ai/continuous-simulation-cli/internal/output"
	"github.com/continuous-labs-ai/continuous-simulation-cli/internal/sdk"
	"github.com/continuous-labs-ai/continuous-simulation-cli/internal/sdk/models/operations"
	"github.com/continuous-labs-ai/continuous-simulation-cli/internal/usage"
	"github.com/spf13/cobra"
)

var getSimulationCmdMeta = []flagutil.FlagMeta{
	{FlagName: "id", Shorthand: "i", FieldPath: "ID", Kind: flagutil.FlagKindString, Required: true, Description: "Stable Simulation ID. [required]"},
}

// initGetSimulationCmd initializes the get-simulation command.
func initGetSimulationCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "get",
		Short:   "Get Simulation",
		Long:    "Returns a Simulation and its current runtime status. The response does not include data-plane tokens.",
		Example: "  continuous simulations get --id <id>",
		RunE:    runGetSimulationCmd,
	}
	flagutil.RegisterFlags(cmd, getSimulationCmdMeta)
	if err := flagutil.ValidateMeta[operations.GetSimulationRequest](getSimulationCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for get-simulation: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runGetSimulationCmd executes the get-simulation command.
func runGetSimulationCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, getSimulationCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, getSimulationCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.GetSimulationRequest](cmd, getSimulationCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Simulations.GetSimulation(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
