// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package simulations

import (
	"fmt"
	"github.com/continuous-labs-ai/cli/internal/client"
	"github.com/continuous-labs-ai/cli/internal/flagutil"
	"github.com/continuous-labs-ai/cli/internal/interactive"
	"github.com/continuous-labs-ai/cli/internal/output"
	"github.com/continuous-labs-ai/cli/internal/sdk"
	"github.com/continuous-labs-ai/cli/internal/sdk/models/operations"
	"github.com/continuous-labs-ai/cli/internal/usage"
	"github.com/spf13/cobra"
)

var getSimulationAdvanceCmdMeta = []flagutil.FlagMeta{
	{FlagName: "id", Shorthand: "i", FieldPath: "ID", Kind: flagutil.FlagKindString, Required: true, Description: "Simulation or World ID. [required]"},
	{FlagName: "advance-id", Shorthand: "a", FieldPath: "AdvanceID", Kind: flagutil.FlagKindString, Required: true, Description: "Clock advance operation ID. [required]"},
}

// initGetSimulationAdvanceCmd initializes the get-simulation-advance command.
func initGetSimulationAdvanceCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "get-simulation-advance",
		Short:   "Get Simulation Clock Advance",
		Long:    "Returns durable clock progress, the event count, and the committed step or failure.",
		Example: "  continuous simulations get-simulation-advance --id <id> --advance-id <id>",
		RunE:    runGetSimulationAdvanceCmd,
		Aliases: []string{"gsa"},
	}
	flagutil.RegisterFlags(cmd, getSimulationAdvanceCmdMeta)
	if err := flagutil.ValidateMeta[operations.GetSimulationAdvanceRequest](getSimulationAdvanceCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for get-simulation-advance: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runGetSimulationAdvanceCmd executes the get-simulation-advance command.
func runGetSimulationAdvanceCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, getSimulationAdvanceCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, getSimulationAdvanceCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.GetSimulationAdvanceRequest](cmd, getSimulationAdvanceCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Simulations.GetSimulationAdvance(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
