// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package simulations

import (
	"fmt"
	"github.com/continuous-labs-ai/cli/internal/client"
	"github.com/continuous-labs-ai/cli/internal/flagutil"
	"github.com/continuous-labs-ai/cli/internal/interactive"
	"github.com/continuous-labs-ai/cli/internal/output"
	"github.com/continuous-labs-ai/cli/internal/sdk"
	"github.com/continuous-labs-ai/cli/internal/sdk/models/operations"
	"github.com/continuous-labs-ai/cli/internal/usage"
	"github.com/spf13/cobra"
)

var listSimulationAdvanceEventsCmdMeta = []flagutil.FlagMeta{
	{FlagName: "id", Shorthand: "i", FieldPath: "ID", Kind: flagutil.FlagKindString, Required: true, Description: "Simulation ID. [required]"},
	{FlagName: "advance-id", Shorthand: "a", FieldPath: "AdvanceID", Kind: flagutil.FlagKindString, Required: true, Description: "Advance ID. A historical fork can read inherited runtime receipts. [required]"},
	{FlagName: "cursor", Shorthand: "c", FieldPath: "Cursor", Kind: flagutil.FlagKindString, Optional: true, Description: "Cursor from the previous page."},
	{FlagName: "limit", Shorthand: "l", FieldPath: "Limit", Kind: flagutil.FlagKindInt64, Optional: true, HasDefault: true, DefaultInt: 50, Description: "Page size, up to 200."},
}

// initListSimulationAdvanceEventsCmd initializes the list-simulation-advance-events command.
func initListSimulationAdvanceEventsCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "list-simulation-advance-events",
		Short:   "List Clock Advance Events",
		Long:    "Returns the ordered event trace for a committed advance. The Simulation must be running or paused. Forks retain traces in their inherited state.",
		Example: "  continuous simulations list-simulation-advance-events --id <id> --advance-id <id>",
		RunE:    runListSimulationAdvanceEventsCmd,
		Aliases: []string{"lsae"},
	}
	flagutil.RegisterFlags(cmd, listSimulationAdvanceEventsCmdMeta)
	if err := flagutil.ValidateMeta[operations.ListSimulationAdvanceEventsRequest](listSimulationAdvanceEventsCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for list-simulation-advance-events: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runListSimulationAdvanceEventsCmd executes the list-simulation-advance-events command.
func runListSimulationAdvanceEventsCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, listSimulationAdvanceEventsCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, listSimulationAdvanceEventsCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.ListSimulationAdvanceEventsRequest](cmd, listSimulationAdvanceEventsCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Simulations.ListSimulationAdvanceEvents(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
