// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package simulations

import (
	"fmt"
	"github.com/continuous-labs-ai/cli/internal/client"
	"github.com/continuous-labs-ai/cli/internal/flagutil"
	"github.com/continuous-labs-ai/cli/internal/interactive"
	"github.com/continuous-labs-ai/cli/internal/output"
	"github.com/continuous-labs-ai/cli/internal/sdk"
	"github.com/continuous-labs-ai/cli/internal/sdk/models/operations"
	"github.com/continuous-labs-ai/cli/internal/usage"
	"github.com/spf13/cobra"
)

var listSimulationStepsCmdMeta = []flagutil.FlagMeta{
	{FlagName: "id", Shorthand: "i", FieldPath: "ID", Kind: flagutil.FlagKindString, Required: true, Description: "Stable Simulation ID. [required]"},
	{FlagName: "cursor", Shorthand: "c", FieldPath: "Cursor", Kind: flagutil.FlagKindString, Optional: true, Description: "Opaque next_cursor value from a previous page."},
	{FlagName: "limit", Shorthand: "l", FieldPath: "Limit", Kind: flagutil.FlagKindInt64, Optional: true, HasDefault: true, DefaultInt: 50, Description: "Page size. Values below 1 use 50. Values above 200 use 200."},
}

// initListSimulationStepsCmd initializes the list-simulation-steps command.
func initListSimulationStepsCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "list-simulation-steps",
		Short:   "List Simulation Steps",
		Long:    "Returns recorded steps for a running or paused Simulation. Use any step to create a deterministic fork.",
		Example: "  continuous simulations list-simulation-steps --id <id>",
		RunE:    runListSimulationStepsCmd,
		Aliases: []string{"lss"},
	}
	flagutil.RegisterFlags(cmd, listSimulationStepsCmdMeta)
	if err := flagutil.ValidateMeta[operations.ListSimulationStepsRequest](listSimulationStepsCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for list-simulation-steps: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runListSimulationStepsCmd executes the list-simulation-steps command.
func runListSimulationStepsCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, listSimulationStepsCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, listSimulationStepsCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.ListSimulationStepsRequest](cmd, listSimulationStepsCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Simulations.ListSimulationSteps(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
