// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package simulations

import (
	"fmt"
	"github.com/continuous-labs-ai/continuous-simulation-cli/internal/client"
	"github.com/continuous-labs-ai/continuous-simulation-cli/internal/flagutil"
	"github.com/continuous-labs-ai/continuous-simulation-cli/internal/interactive"
	"github.com/continuous-labs-ai/continuous-simulation-cli/internal/output"
	"github.com/continuous-labs-ai/continuous-simulation-cli/internal/sdk"
	"github.com/continuous-labs-ai/continuous-simulation-cli/internal/sdk/models/operations"
	"github.com/continuous-labs-ai/continuous-simulation-cli/internal/usage"
	"github.com/spf13/cobra"
)

var mintSimulationTokenCmdMeta = []flagutil.FlagMeta{
	{FlagName: "id", Shorthand: "i", FieldPath: "ID", Kind: flagutil.FlagKindString, Required: true, Description: "Stable Simulation ID. [required]"},
	{FlagName: "ttl-seconds", Shorthand: "t", FieldPath: "Body.TTLSeconds", Kind: flagutil.FlagKindInt64, Required: true, Description: "Token lifetime in seconds, from 60 through 86,400. [required]"},
}

// initMintSimulationTokenCmd initializes the mint-simulation-token command.
func initMintSimulationTokenCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "mint-simulation-token",
		Short:   "Mint Simulation Token",
		Long:    "Mints an expiring data-plane token. Send it in X-Continuous-Simulation-Token. Other unexpired tokens remain valid.",
		Example: "  continuous simulations mint-simulation-token --id <id> --ttl-seconds 3600",
		RunE:    runMintSimulationTokenCmd,
		Aliases: []string{"mst"},
	}
	flagutil.RegisterFlags(cmd, mintSimulationTokenCmdMeta)
	if err := flagutil.ValidateMeta[operations.MintSimulationTokenRequest](mintSimulationTokenCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for mint-simulation-token: %w", err)
	}
	cmd.Flags().String("body", "", "Request body as JSON (alternative to individual flags). Can also be provided via stdin.")
	parent.AddCommand(cmd)
	return nil
}

// runMintSimulationTokenCmd executes the mint-simulation-token command.
func runMintSimulationTokenCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, mintSimulationTokenCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, mintSimulationTokenCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.MintSimulationTokenRequest](cmd, mintSimulationTokenCmdMeta, "Body", "body")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Simulations.MintSimulationToken(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
