// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package simulations

import (
	"fmt"
	"github.com/continuous-labs-ai/cli/internal/client"
	"github.com/continuous-labs-ai/cli/internal/flagutil"
	"github.com/continuous-labs-ai/cli/internal/interactive"
	"github.com/continuous-labs-ai/cli/internal/output"
	"github.com/continuous-labs-ai/cli/internal/sdk"
	"github.com/continuous-labs-ai/cli/internal/sdk/models/operations"
	"github.com/continuous-labs-ai/cli/internal/usage"
	"github.com/spf13/cobra"
)

var regenerateSimulationTokenCmdMeta = []flagutil.FlagMeta{
	{FlagName: "id", FieldPath: "ID", Kind: flagutil.FlagKindString, Required: true, Description: "Simulation ID. [required]"},
	{FlagName: "idempotency-key", FieldPath: "IdempotencyKey", Kind: flagutil.FlagKindString, Required: true, Description: "Stable key for this regeneration request. [required]"},
}

// initRegenerateSimulationTokenCmd initializes the regenerate-simulation-token command.
func initRegenerateSimulationTokenCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "regenerate-simulation-token",
		Short:   "Regenerate Simulation Token",
		Long:    "Explicitly replaces the current Simulation credential. The previous token stops authenticating when the transaction commits. Reuse the Idempotency-Key to retry safely.",
		Example: "  continuous simulations regenerate-simulation-token --id <id> --idempotency-key <value>",
		RunE:    runRegenerateSimulationTokenCmd,
		Aliases: []string{"rst"},
	}
	flagutil.RegisterFlags(cmd, regenerateSimulationTokenCmdMeta)
	if err := flagutil.ValidateMeta[operations.RegenerateSimulationTokenRequest](regenerateSimulationTokenCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for regenerate-simulation-token: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runRegenerateSimulationTokenCmd executes the regenerate-simulation-token command.
func runRegenerateSimulationTokenCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, regenerateSimulationTokenCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, regenerateSimulationTokenCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.RegenerateSimulationTokenRequest](cmd, regenerateSimulationTokenCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Simulations.RegenerateSimulationToken(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
