// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package simulations

import (
	"github.com/continuous-labs-ai/cli/internal/usage"
	"github.com/spf13/cobra"
)

func InitSimulationsRoot(parent *cobra.Command) error {
	var SimulationsCmd = &cobra.Command{
		Use:   "simulations",
		Short: "Create and control isolated runtime instances of ready Simulators",
		Long:  "Create and control isolated runtime instances of ready Simulators.",
		RunE: func(cmd *cobra.Command, args []string) error {
			if usage.UsageRequested(cmd) {
				return usage.EmitSchema(cmd, cmd.OutOrStdout())
			}
			return cmd.Help()
		},
	}

	if err := initListSimulationsCmd(SimulationsCmd); err != nil {
		return err
	}

	if err := initCreateSimulationCmd(SimulationsCmd); err != nil {
		return err
	}

	if err := initDeleteSimulationCmd(SimulationsCmd); err != nil {
		return err
	}

	if err := initGetSimulationCmd(SimulationsCmd); err != nil {
		return err
	}

	if err := initForkSimulationCmd(SimulationsCmd); err != nil {
		return err
	}

	if err := initStartSimulationCmd(SimulationsCmd); err != nil {
		return err
	}

	if err := initListSimulationStepsCmd(SimulationsCmd); err != nil {
		return err
	}

	if err := initStopSimulationCmd(SimulationsCmd); err != nil {
		return err
	}

	if err := initMintSimulationTokenCmd(SimulationsCmd); err != nil {
		return err
	}

	parent.AddCommand(SimulationsCmd)
	return nil
}
