// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package simulations

import (
	"fmt"
	"github.com/continuous-labs-ai/cli/internal/client"
	"github.com/continuous-labs-ai/cli/internal/flagutil"
	"github.com/continuous-labs-ai/cli/internal/interactive"
	"github.com/continuous-labs-ai/cli/internal/output"
	"github.com/continuous-labs-ai/cli/internal/sdk"
	"github.com/continuous-labs-ai/cli/internal/sdk/models/operations"
	"github.com/continuous-labs-ai/cli/internal/usage"
	"github.com/spf13/cobra"
)

var startSimulationCmdMeta = []flagutil.FlagMeta{
	{FlagName: "id", Shorthand: "i", FieldPath: "ID", Kind: flagutil.FlagKindString, Required: true, Description: "Stable Simulation ID. [required]"},
}

// initStartSimulationCmd initializes the start-simulation command.
func initStartSimulationCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "start",
		Short:   "Start Simulation",
		Long:    "Starts a stopped Simulation from its saved runtime state. Its endpoint becomes available after the runtime starts.",
		Example: "  continuous simulations start --id <id>",
		RunE:    runStartSimulationCmd,
	}
	flagutil.RegisterFlags(cmd, startSimulationCmdMeta)
	if err := flagutil.ValidateMeta[operations.StartSimulationRequest](startSimulationCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for start-simulation: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runStartSimulationCmd executes the start-simulation command.
func runStartSimulationCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, startSimulationCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, startSimulationCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.StartSimulationRequest](cmd, startSimulationCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Simulations.StartSimulation(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
