// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package simulations

import (
	"fmt"
	"github.com/continuous-labs-ai/cli/internal/client"
	"github.com/continuous-labs-ai/cli/internal/flagutil"
	"github.com/continuous-labs-ai/cli/internal/interactive"
	"github.com/continuous-labs-ai/cli/internal/output"
	"github.com/continuous-labs-ai/cli/internal/sdk"
	"github.com/continuous-labs-ai/cli/internal/sdk/models/operations"
	"github.com/continuous-labs-ai/cli/internal/usage"
	"github.com/spf13/cobra"
)

var stopSimulationCmdMeta = []flagutil.FlagMeta{
	{FlagName: "id", Shorthand: "i", FieldPath: "ID", Kind: flagutil.FlagKindString, Required: true, Description: "Stable Simulation ID. [required]"},
}

// initStopSimulationCmd initializes the stop-simulation command.
func initStopSimulationCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "stop",
		Short:   "Stop Simulation",
		Long:    "Stops a Simulation and saves its runtime state. You can start it later from the saved state.",
		Example: "  continuous simulations stop --id <id>",
		RunE:    runStopSimulationCmd,
	}
	flagutil.RegisterFlags(cmd, stopSimulationCmdMeta)
	if err := flagutil.ValidateMeta[operations.StopSimulationRequest](stopSimulationCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for stop-simulation: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runStopSimulationCmd executes the stop-simulation command.
func runStopSimulationCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, stopSimulationCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, stopSimulationCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.StopSimulationRequest](cmd, stopSimulationCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Simulations.StopSimulation(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
