// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package cli

import (
	"fmt"
	"github.com/continuous-labs-ai/continuous-simulation-cli/internal/config"
	"github.com/continuous-labs-ai/continuous-simulation-cli/internal/usage"
	"github.com/spf13/cobra"
)

// initWhoamiCmd initializes the whoami command.
func initWhoamiCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:   "whoami",
		Short: "Display current authentication configuration",
		Long: `Display the currently configured settings and their sources.

Sources are shown as:
  [flag]    - Set via command line flag
  [env]     - Set via environment variable (CONTINUOUS_*)
  [keyring] - Set via OS keychain (stored by configure command)
  [config]  - Set via config file (~/.config/continuous/config.yaml)
  [unset]   - Not configured

Credential values are masked for security.`,
		RunE: runWhoamiCmd,
	}
	parent.AddCommand(cmd)
	return nil
}

// runWhoamiCmd executes the whoami command.
func runWhoamiCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	out := cmd.OutOrStdout()
	fmt.Fprintln(out, "Configuration")
	fmt.Fprintln(out, "=============")
	fmt.Fprintln(out)
	fmt.Fprintf(out, "Config file: %s\n", config.GetConfigPath())
	fmt.Fprintf(out, "Environment prefix: CONTINUOUS_\n")
	fmt.Fprintln(out)
	fmt.Fprintln(out, "Credentials:")

	// Use a Continuous API key. Send it in the Authorization header as a Bearer token.
	{
		value, source := config.ResolveSecurityCredential(cmd, "api-key-auth")
		fmt.Fprintf(out, "  --%-25s [%-7s] %s\n", "api-key-auth", source, maskSecret(value))
	}

	return nil
}
