// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package credentials

import (
	"fmt"
	"github.com/continuous-labs-ai/cli/internal/client"
	"github.com/continuous-labs-ai/cli/internal/flagutil"
	"github.com/continuous-labs-ai/cli/internal/interactive"
	"github.com/continuous-labs-ai/cli/internal/output"
	"github.com/continuous-labs-ai/cli/internal/sdk"
	"github.com/continuous-labs-ai/cli/internal/sdk/models/components"
	"github.com/continuous-labs-ai/cli/internal/sdk/models/operations"
	"github.com/continuous-labs-ai/cli/internal/usage"
	"github.com/spf13/cobra"
)

var createCredentialCmdMeta = []flagutil.FlagMeta{
	{FlagName: "base-url", Shorthand: "b", FieldPath: "BaseURL", Kind: flagutil.FlagKindString, Required: true, Description: "The https URL of the real system. Requests go to paths under it. [required]"},
	{FlagName: "header", FieldPath: "Header", Kind: flagutil.FlagKindString, Optional: true, HasDefault: true, DefaultStr: "Authorization", Description: "The HTTP header that carries the value."},
	{FlagName: "name", Shorthand: "n", FieldPath: "Name", Kind: flagutil.FlagKindString, Required: true, Description: "Credential name. [required]"},
	{FlagName: "value", Shorthand: "v", FieldPath: "Value", Kind: flagutil.FlagKindString, Required: true, Description: "The full header value, for example Bearer followed by a token. The API never returns it. [required]"},
}

// initCreateCredentialCmd initializes the create-credential command.
func initCreateCredentialCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "create",
		Short:   "Create credential",
		Long:    "Stores a connection to a real system: its base URL, the header that carries the credential, and the header value. Returns the credential without its value.",
		Example: "  continuous credentials create --base-url https://api.stripe.com --name stripe-test --value Bearer <redacted>",
		RunE:    runCreateCredentialCmd,
	}
	flagutil.RegisterFlags(cmd, createCredentialCmdMeta)
	if err := flagutil.ValidateMeta[components.CreateCredentialRequest](createCredentialCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for create-credential: %w", err)
	}
	cmd.Flags().String("body", "", "Request body as JSON (alternative to individual flags). Can also be provided via stdin.")
	parent.AddCommand(cmd)
	return nil
}

// runCreateCredentialCmd executes the create-credential command.
func runCreateCredentialCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, createCredentialCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, createCredentialCmdMeta); err != nil {
			return err
		}
	}
	request, err := flagutil.BuildRequest[components.CreateCredentialRequest](cmd, createCredentialCmdMeta, "", "body")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Credentials.CreateCredential(cmd.Context(), *request, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
