// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package credentials

import (
	"fmt"
	"github.com/continuous-labs-ai/cli/internal/client"
	"github.com/continuous-labs-ai/cli/internal/flagutil"
	"github.com/continuous-labs-ai/cli/internal/interactive"
	"github.com/continuous-labs-ai/cli/internal/output"
	"github.com/continuous-labs-ai/cli/internal/sdk"
	"github.com/continuous-labs-ai/cli/internal/sdk/models/operations"
	"github.com/continuous-labs-ai/cli/internal/usage"
	"github.com/spf13/cobra"
)

var listCredentialsCmdMeta = []flagutil.FlagMeta{
	{FlagName: "limit", Shorthand: "l", FieldPath: "Limit", Kind: flagutil.FlagKindInt64, Optional: true, HasDefault: true, DefaultInt: 50, Description: "Page size. Values below 1 use 50. Values above 200 use 200."},
	{FlagName: "cursor", Shorthand: "c", FieldPath: "Cursor", Kind: flagutil.FlagKindString, Optional: true, Description: "Opaque next_cursor value from a previous page."},
}

// initListCredentialsCmd initializes the list-credentials command.
func initListCredentialsCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "list",
		Short:   "List credentials",
		Long:    "Returns the workspace's credentials, newest first. Credential values are never returned.",
		Example: "  continuous credentials list",
		RunE:    runListCredentialsCmd,
	}
	flagutil.RegisterFlags(cmd, listCredentialsCmdMeta)
	if err := flagutil.ValidateMeta[operations.ListCredentialsRequest](listCredentialsCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for list-credentials: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runListCredentialsCmd executes the list-credentials command.
func runListCredentialsCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, listCredentialsCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, listCredentialsCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.ListCredentialsRequest](cmd, listCredentialsCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Credentials.ListCredentials(cmd.Context(), req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
