// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package credentials

import (
	"github.com/continuous-labs-ai/cli/internal/usage"
	"github.com/spf13/cobra"
)

func InitCredentialsRoot(parent *cobra.Command) error {
	var CredentialsCmd = &cobra.Command{
		Use:   "credentials",
		Short: "Store connections to real systems: a base URL, the header that carries the credential, and its value",
		Long:  "Store connections to real systems: a base URL, the header that carries the credential, and its value. The API never returns a value.",
		RunE: func(cmd *cobra.Command, args []string) error {
			if usage.UsageRequested(cmd) {
				return usage.EmitSchema(cmd, cmd.OutOrStdout())
			}
			return cmd.Help()
		},
	}

	if err := initListCredentialsCmd(CredentialsCmd); err != nil {
		return err
	}

	if err := initCreateCredentialCmd(CredentialsCmd); err != nil {
		return err
	}

	if err := initDeleteCredentialCmd(CredentialsCmd); err != nil {
		return err
	}

	if err := initGetCredentialCmd(CredentialsCmd); err != nil {
		return err
	}

	if err := initUpdateCredentialCmd(CredentialsCmd); err != nil {
		return err
	}

	parent.AddCommand(CredentialsCmd)
	return nil
}
