// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package worlds

import (
	"fmt"
	"github.com/continuous-labs-ai/cli/internal/client"
	"github.com/continuous-labs-ai/cli/internal/flagutil"
	"github.com/continuous-labs-ai/cli/internal/interactive"
	"github.com/continuous-labs-ai/cli/internal/output"
	"github.com/continuous-labs-ai/cli/internal/sdk"
	"github.com/continuous-labs-ai/cli/internal/sdk/models/operations"
	"github.com/continuous-labs-ai/cli/internal/usage"
	"github.com/spf13/cobra"
)

var advanceWorldTimeCmdMeta = []flagutil.FlagMeta{
	{FlagName: "id", FieldPath: "ID", Kind: flagutil.FlagKindString, Required: true, Description: "Simulation or World ID. [required]"},
	{FlagName: "idempotency-key", FieldPath: "IdempotencyKey", Kind: flagutil.FlagKindString, Required: true, Description: "Stable key for this request. Reuse with the same target returns the same operation. [required]"},
	{FlagName: "to", Shorthand: "t", FieldPath: "Body.To", Kind: flagutil.FlagKindDateTime, Required: true, Description: "Absolute target time in RFC 3339, with at most millisecond precision. [required]"},
}

// initAdvanceWorldTimeCmd initializes the advance-world-time command.
func initAdvanceWorldTimeCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "advance-world-time",
		Short:   "Advance World Time",
		Long:    "Fences all members, advances each local clock, and returns a durable operation. A partial failure keeps members fenced while the operation retries. The World clock changes after all members commit.",
		Example: "  continuous worlds advance-world-time --id <id> --idempotency-key <value> --to 2026-11-05T04:15:58.628Z",
		RunE:    runAdvanceWorldTimeCmd,
		Aliases: []string{"awt"},
	}
	flagutil.RegisterFlags(cmd, advanceWorldTimeCmdMeta)
	if err := flagutil.ValidateMeta[operations.AdvanceWorldTimeRequest](advanceWorldTimeCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for advance-world-time: %w", err)
	}
	cmd.Flags().String("body", "", "Request body as JSON (alternative to individual flags). Can also be provided via stdin.")
	parent.AddCommand(cmd)
	return nil
}

// runAdvanceWorldTimeCmd executes the advance-world-time command.
func runAdvanceWorldTimeCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, advanceWorldTimeCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, advanceWorldTimeCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.AdvanceWorldTimeRequest](cmd, advanceWorldTimeCmdMeta, "Body", "body")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Worlds.AdvanceWorldTime(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
