// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package worlds

import (
	"fmt"
	"github.com/continuous-labs-ai/cli/internal/client"
	"github.com/continuous-labs-ai/cli/internal/flagutil"
	"github.com/continuous-labs-ai/cli/internal/interactive"
	"github.com/continuous-labs-ai/cli/internal/output"
	"github.com/continuous-labs-ai/cli/internal/sdk"
	"github.com/continuous-labs-ai/cli/internal/sdk/models/components"
	"github.com/continuous-labs-ai/cli/internal/sdk/models/operations"
	"github.com/continuous-labs-ai/cli/internal/usage"
	"github.com/spf13/cobra"
)

var buildWorldCmdMeta = []flagutil.FlagMeta{
	{FlagName: "builder", Shorthand: "b", FieldPath: "Builder", Kind: flagutil.FlagKindEnum, Optional: true, HasDefault: true, DefaultStr: "claude", EnumValues: []string{"openai", "claude"}, Description: "Model provider that builds starting data. Defaults to claude. (options: openai, claude)"},
	{FlagName: "instructions", Shorthand: "i", FieldPath: "Instructions", Kind: flagutil.FlagKindString, Optional: true, Description: "Describe the initial data, scenario, and relationships. Populated Worlds support up to 8 selected Simulators and 1,000 starting records in total. Named record types replace their default data. At most 16,384 characters and 65,536 UTF-8 bytes. U+0000 is not permitted."},
	{FlagName: "simulators", Shorthand: "s", FieldPath: "Simulators", Kind: flagutil.FlagKindStringArray, Required: true, Description: "Simulator IDs for the World. [required]"},
}

// initBuildWorldCmd initializes the build-world command.
func initBuildWorldCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "build",
		Short:   "Build World",
		Long:    "Starts an asynchronous World build from ready Simulators and returns it in the building state. Instructions generate and validate initial synthetic data. Start the World once it is ready to create its Simulations.",
		Example: "  continuous worlds build --simulators '[\"smr_01J8Z5X4K7M2N9P0Q1R2S3T4V5\"]'",
		RunE:    runBuildWorldCmd,
	}
	flagutil.RegisterFlags(cmd, buildWorldCmdMeta)
	if err := flagutil.ValidateMeta[components.BuildWorldRequest](buildWorldCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for build-world: %w", err)
	}
	cmd.Flags().String("body", "", "Request body as JSON (alternative to individual flags). Can also be provided via stdin.")
	parent.AddCommand(cmd)
	return nil
}

// runBuildWorldCmd executes the build-world command.
func runBuildWorldCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, buildWorldCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, buildWorldCmdMeta); err != nil {
			return err
		}
	}
	request, err := flagutil.BuildRequest[components.BuildWorldRequest](cmd, buildWorldCmdMeta, "", "body")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Worlds.BuildWorld(cmd.Context(), *request, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
