// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package worlds

import (
	"fmt"
	"github.com/continuous-labs-ai/cli/internal/client"
	"github.com/continuous-labs-ai/cli/internal/flagutil"
	"github.com/continuous-labs-ai/cli/internal/interactive"
	"github.com/continuous-labs-ai/cli/internal/output"
	"github.com/continuous-labs-ai/cli/internal/sdk"
	"github.com/continuous-labs-ai/cli/internal/sdk/models/operations"
	"github.com/continuous-labs-ai/cli/internal/usage"
	"github.com/spf13/cobra"
)

var cancelWorldCmdMeta = []flagutil.FlagMeta{
	{FlagName: "id", Shorthand: "i", FieldPath: "ID", Kind: flagutil.FlagKindString, Required: true, Description: "World ID. [required]"},
}

// initCancelWorldCmd initializes the cancel-world command.
func initCancelWorldCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "cancel",
		Short:   "Cancel World Build",
		Long:    "Cancels an active World build. Repeated cancellation returns the current World.",
		Example: "  continuous worlds cancel --id <id>",
		RunE:    runCancelWorldCmd,
	}
	flagutil.RegisterFlags(cmd, cancelWorldCmdMeta)
	if err := flagutil.ValidateMeta[operations.CancelWorldRequest](cancelWorldCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for cancel-world: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runCancelWorldCmd executes the cancel-world command.
func runCancelWorldCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, cancelWorldCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, cancelWorldCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.CancelWorldRequest](cmd, cancelWorldCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Worlds.CancelWorld(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
