// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package worlds

import (
	"fmt"
	"github.com/continuous-labs-ai/cli/internal/client"
	"github.com/continuous-labs-ai/cli/internal/flagutil"
	"github.com/continuous-labs-ai/cli/internal/interactive"
	"github.com/continuous-labs-ai/cli/internal/output"
	"github.com/continuous-labs-ai/cli/internal/sdk"
	"github.com/continuous-labs-ai/cli/internal/sdk/models/operations"
	"github.com/continuous-labs-ai/cli/internal/usage"
	"github.com/spf13/cobra"
)

var getWorldAdvanceCmdMeta = []flagutil.FlagMeta{
	{FlagName: "id", Shorthand: "i", FieldPath: "ID", Kind: flagutil.FlagKindString, Required: true, Description: "Simulation or World ID. [required]"},
	{FlagName: "advance-id", Shorthand: "a", FieldPath: "AdvanceID", Kind: flagutil.FlagKindString, Required: true, Description: "Clock advance operation ID. [required]"},
}

// initGetWorldAdvanceCmd initializes the get-world-advance command.
func initGetWorldAdvanceCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "get-world-advance",
		Short:   "Get World Clock Advance",
		Long:    "Returns durable progress for each member. Members remain fenced until the whole advance can finish.",
		Example: "  continuous worlds get-world-advance --id <id> --advance-id <id>",
		RunE:    runGetWorldAdvanceCmd,
		Aliases: []string{"gwa"},
	}
	flagutil.RegisterFlags(cmd, getWorldAdvanceCmdMeta)
	if err := flagutil.ValidateMeta[operations.GetWorldAdvanceRequest](getWorldAdvanceCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for get-world-advance: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runGetWorldAdvanceCmd executes the get-world-advance command.
func runGetWorldAdvanceCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, getWorldAdvanceCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, getWorldAdvanceCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.GetWorldAdvanceRequest](cmd, getWorldAdvanceCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Worlds.GetWorldAdvance(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
