// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package worlds

import (
	"fmt"
	"github.com/continuous-labs-ai/cli/internal/client"
	"github.com/continuous-labs-ai/cli/internal/flagutil"
	"github.com/continuous-labs-ai/cli/internal/interactive"
	"github.com/continuous-labs-ai/cli/internal/output"
	"github.com/continuous-labs-ai/cli/internal/sdk"
	"github.com/continuous-labs-ai/cli/internal/sdk/models/operations"
	"github.com/continuous-labs-ai/cli/internal/usage"
	"github.com/spf13/cobra"
)

var listWorldsCmdMeta = []flagutil.FlagMeta{
	{FlagName: "limit", Shorthand: "l", FieldPath: "Limit", Kind: flagutil.FlagKindInt64, Optional: true, HasDefault: true, DefaultInt: 50, Description: "Page size. Values below 1 use 50. Values above 200 use 200."},
	{FlagName: "cursor", Shorthand: "c", FieldPath: "Cursor", Kind: flagutil.FlagKindString, Optional: true, Description: "Opaque cursor from the previous page."},
}

// initListWorldsCmd initializes the list-worlds command.
func initListWorldsCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "list",
		Short:   "List Worlds",
		Long:    "Returns all Worlds that the API key can access.",
		Example: "  continuous worlds list",
		RunE:    runListWorldsCmd,
	}
	flagutil.RegisterFlags(cmd, listWorldsCmdMeta)
	if err := flagutil.ValidateMeta[operations.ListWorldsRequest](listWorldsCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for list-worlds: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runListWorldsCmd executes the list-worlds command.
func runListWorldsCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, listWorldsCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, listWorldsCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.ListWorldsRequest](cmd, listWorldsCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Worlds.ListWorlds(cmd.Context(), req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
