// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package worlds

import (
	"fmt"
	"github.com/continuous-labs-ai/cli/internal/client"
	"github.com/continuous-labs-ai/cli/internal/flagutil"
	"github.com/continuous-labs-ai/cli/internal/interactive"
	"github.com/continuous-labs-ai/cli/internal/output"
	"github.com/continuous-labs-ai/cli/internal/sdk"
	"github.com/continuous-labs-ai/cli/internal/sdk/models/operations"
	"github.com/continuous-labs-ai/cli/internal/usage"
	"github.com/spf13/cobra"
)

var startWorldCmdMeta = []flagutil.FlagMeta{
	{FlagName: "id", Shorthand: "i", FieldPath: "ID", Kind: flagutil.FlagKindString, Required: true, Description: "Stable World ID. [required]"},
}

// initStartWorldCmd initializes the start-world command.
func initStartWorldCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "start",
		Short:   "Start World",
		Long:    "Creates member Simulations on first start. Later starts restore stopped Simulations from saved state.",
		Example: "  continuous worlds start --id <id>",
		RunE:    runStartWorldCmd,
	}
	flagutil.RegisterFlags(cmd, startWorldCmdMeta)
	if err := flagutil.ValidateMeta[operations.StartWorldRequest](startWorldCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for start-world: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runStartWorldCmd executes the start-world command.
func runStartWorldCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, startWorldCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, startWorldCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.StartWorldRequest](cmd, startWorldCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Worlds.StartWorld(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
