// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package worlds

import (
	"fmt"
	"github.com/continuous-labs-ai/continuous-simulation-cli/internal/client"
	"github.com/continuous-labs-ai/continuous-simulation-cli/internal/flagutil"
	"github.com/continuous-labs-ai/continuous-simulation-cli/internal/interactive"
	"github.com/continuous-labs-ai/continuous-simulation-cli/internal/output"
	"github.com/continuous-labs-ai/continuous-simulation-cli/internal/sdk"
	"github.com/continuous-labs-ai/continuous-simulation-cli/internal/sdk/models/operations"
	"github.com/continuous-labs-ai/continuous-simulation-cli/internal/usage"
	"github.com/spf13/cobra"
)

var stopWorldCmdMeta = []flagutil.FlagMeta{
	{FlagName: "id", Shorthand: "i", FieldPath: "ID", Kind: flagutil.FlagKindString, Required: true, Description: "Stable World ID. [required]"},
}

// initStopWorldCmd initializes the stop-world command.
func initStopWorldCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "stop",
		Short:   "Stop World",
		Long:    "Stops a World and saves each Simulation state. You can start the World later from the saved states.",
		Example: "  continuous worlds stop --id <id>",
		RunE:    runStopWorldCmd,
	}
	flagutil.RegisterFlags(cmd, stopWorldCmdMeta)
	if err := flagutil.ValidateMeta[operations.StopWorldRequest](stopWorldCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for stop-world: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runStopWorldCmd executes the stop-world command.
func runStopWorldCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, stopWorldCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, stopWorldCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.StopWorldRequest](cmd, stopWorldCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Worlds.StopWorld(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
