// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package simulators

import (
	"fmt"
	"github.com/continuous-labs-ai/cli/internal/client"
	"github.com/continuous-labs-ai/cli/internal/flagutil"
	"github.com/continuous-labs-ai/cli/internal/interactive"
	"github.com/continuous-labs-ai/cli/internal/output"
	"github.com/continuous-labs-ai/cli/internal/sdk"
	"github.com/continuous-labs-ai/cli/internal/sdk/models/operations"
	"github.com/continuous-labs-ai/cli/internal/usage"
	"github.com/spf13/cobra"
)

var cancelSimulatorCmdMeta = []flagutil.FlagMeta{
	{FlagName: "id", Shorthand: "i", FieldPath: "ID", Kind: flagutil.FlagKindString, Required: true, Description: "Simulator ID. [required]"},
}

// initCancelSimulatorCmd initializes the cancel-simulator command.
func initCancelSimulatorCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "cancel",
		Short:   "Cancel Simulator Build",
		Long:    "Requests cancellation of an active Simulator build. The build can finish before cancellation takes effect. A Simulator that is not building is returned unchanged.",
		Example: "  continuous simulators cancel --id <id>",
		RunE:    runCancelSimulatorCmd,
	}
	flagutil.RegisterFlags(cmd, cancelSimulatorCmdMeta)
	if err := flagutil.ValidateMeta[operations.CancelSimulatorRequest](cancelSimulatorCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for cancel-simulator: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runCancelSimulatorCmd executes the cancel-simulator command.
func runCancelSimulatorCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, cancelSimulatorCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, cancelSimulatorCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.CancelSimulatorRequest](cmd, cancelSimulatorCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Simulators.CancelSimulator(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
