// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package simulators

import (
	"fmt"
	"github.com/continuous-labs-ai/cli/internal/client"
	"github.com/continuous-labs-ai/cli/internal/flagutil"
	"github.com/continuous-labs-ai/cli/internal/interactive"
	"github.com/continuous-labs-ai/cli/internal/output"
	"github.com/continuous-labs-ai/cli/internal/sdk"
	"github.com/continuous-labs-ai/cli/internal/sdk/models/operations"
	"github.com/continuous-labs-ai/cli/internal/usage"
	"github.com/spf13/cobra"
)

var cloneSimulatorCmdMeta = []flagutil.FlagMeta{
	{FlagName: "id", FieldPath: "ID", Kind: flagutil.FlagKindString, Required: true, Description: "Source Simulator ID. [required]"},
	{FlagName: "idempotency-key", FieldPath: "Body.IdempotencyKey", Kind: flagutil.FlagKindString, Required: true, Description: "Stable key for retrying this clone into the target workspace. [required]"},
	{FlagName: "name", Shorthand: "n", FieldPath: "Body.Name", Kind: flagutil.FlagKindString, Optional: true, Description: "Display name for the clone. Defaults to the source Simulator's name."},
	{FlagName: "target-workspace-id", Shorthand: "t", FieldPath: "Body.TargetWorkspaceID", Kind: flagutil.FlagKindString, Required: true, Description: "Workspace that receives the clone. It must differ from the source workspace. [required]"},
}

// initCloneSimulatorCmd initializes the clone-simulator command.
func initCloneSimulatorCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "clone",
		Short:   "Clone Simulator",
		Long:    "Creates a ready copy of a ready Simulator in another workspace. The clone has a new ID and the source's image digest; the source is unchanged. The source is the caller's workspace: an API key's own workspace, or X-Workspace-Id for a session. An API key may clone into any other workspace of its organization.",
		Example: "  continuous simulators clone --id <id> --idempotency-key <value> --target-workspace-id <id>",
		RunE:    runCloneSimulatorCmd,
	}
	flagutil.RegisterFlags(cmd, cloneSimulatorCmdMeta)
	if err := flagutil.ValidateMeta[operations.CloneSimulatorRequest](cloneSimulatorCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for clone-simulator: %w", err)
	}
	cmd.Flags().String("body", "", "Request body as JSON (alternative to individual flags). Can also be provided via stdin.")
	parent.AddCommand(cmd)
	return nil
}

// runCloneSimulatorCmd executes the clone-simulator command.
func runCloneSimulatorCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, cloneSimulatorCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, cloneSimulatorCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.CloneSimulatorRequest](cmd, cloneSimulatorCmdMeta, "Body", "body")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Simulators.CloneSimulator(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
