// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package simulators

import (
	"fmt"
	"github.com/continuous-labs-ai/continuous-simulation-cli/internal/client"
	"github.com/continuous-labs-ai/continuous-simulation-cli/internal/flagutil"
	"github.com/continuous-labs-ai/continuous-simulation-cli/internal/interactive"
	"github.com/continuous-labs-ai/continuous-simulation-cli/internal/output"
	"github.com/continuous-labs-ai/continuous-simulation-cli/internal/sdk"
	"github.com/continuous-labs-ai/continuous-simulation-cli/internal/sdk/models/operations"
	"github.com/continuous-labs-ai/continuous-simulation-cli/internal/usage"
	"github.com/spf13/cobra"
)

var getSimulatorCmdMeta = []flagutil.FlagMeta{
	{FlagName: "id", Shorthand: "i", FieldPath: "ID", Kind: flagutil.FlagKindString, Required: true, Description: "Stable Simulator ID. [required]"},
}

// initGetSimulatorCmd initializes the get-simulator command.
func initGetSimulatorCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "get",
		Short:   "Get Simulator",
		Long:    "Returns a Simulator and its current build status.",
		Example: "  continuous simulators get --id <id>",
		RunE:    runGetSimulatorCmd,
	}
	flagutil.RegisterFlags(cmd, getSimulatorCmdMeta)
	if err := flagutil.ValidateMeta[operations.GetSimulatorRequest](getSimulatorCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for get-simulator: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runGetSimulatorCmd executes the get-simulator command.
func runGetSimulatorCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, getSimulatorCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, getSimulatorCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.GetSimulatorRequest](cmd, getSimulatorCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Simulators.GetSimulator(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
