// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package simulators

import (
	"fmt"
	"github.com/continuous-labs-ai/cli/internal/client"
	"github.com/continuous-labs-ai/cli/internal/flagutil"
	"github.com/continuous-labs-ai/cli/internal/interactive"
	"github.com/continuous-labs-ai/cli/internal/output"
	"github.com/continuous-labs-ai/cli/internal/sdk"
	"github.com/continuous-labs-ai/cli/internal/sdk/models/operations"
	"github.com/continuous-labs-ai/cli/internal/usage"
	"github.com/spf13/cobra"
)

var listSimulatorsCmdMeta = []flagutil.FlagMeta{
	{FlagName: "status", Shorthand: "s", FieldPath: "Status", Kind: flagutil.FlagKindEnum, Optional: true, EnumValues: []string{"building", "ready", "failed", "canceled"}, Description: "Optional build status filter. (options: building, ready, failed, canceled)"},
	{FlagName: "name", Shorthand: "n", FieldPath: "Name", Kind: flagutil.FlagKindString, Optional: true, Description: "Optional exact Simulator name. Prefix a catalog name with continuous/. Names cannot start with smr_."},
	{FlagName: "limit", Shorthand: "l", FieldPath: "Limit", Kind: flagutil.FlagKindInt64, Optional: true, HasDefault: true, DefaultInt: 50, Description: "Page size. Values below 1 use 50. Values above 200 use 200."},
	{FlagName: "cursor", Shorthand: "c", FieldPath: "Cursor", Kind: flagutil.FlagKindString, Optional: true, Description: "Opaque next_cursor value from a previous page."},
}

// initListSimulatorsCmd initializes the list-simulators command.
func initListSimulatorsCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "list",
		Short:   "List Simulators",
		Long:    "Returns all Simulators that the API key can access. Results can be filtered by status or name.",
		Example: "  continuous simulators list",
		RunE:    runListSimulatorsCmd,
	}
	flagutil.RegisterFlags(cmd, listSimulatorsCmdMeta)
	if err := flagutil.ValidateMeta[operations.ListSimulatorsRequest](listSimulatorsCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for list-simulators: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runListSimulatorsCmd executes the list-simulators command.
func runListSimulatorsCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, listSimulatorsCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, listSimulatorsCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.ListSimulatorsRequest](cmd, listSimulatorsCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Simulators.ListSimulators(cmd.Context(), req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
