// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package simulators

import (
	"github.com/continuous-labs-ai/cli/internal/usage"
	"github.com/spf13/cobra"
)

func InitSimulatorsRoot(parent *cobra.Command) error {
	var SimulatorsCmd = &cobra.Command{
		Use:   "simulators",
		Short: "Build Simulators from OpenAPI or WSDL documents, check or cancel a build, and delete Simulators",
		Long:  "Build Simulators from OpenAPI or WSDL documents, check or cancel a build, and delete Simulators.",
		RunE: func(cmd *cobra.Command, args []string) error {
			if usage.UsageRequested(cmd) {
				return usage.EmitSchema(cmd, cmd.OutOrStdout())
			}
			return cmd.Help()
		},
	}

	if err := initListSimulatorsCmd(SimulatorsCmd); err != nil {
		return err
	}

	if err := initBuildSimulatorCmd(SimulatorsCmd); err != nil {
		return err
	}

	if err := initDeleteSimulatorCmd(SimulatorsCmd); err != nil {
		return err
	}

	if err := initGetSimulatorCmd(SimulatorsCmd); err != nil {
		return err
	}

	if err := initCancelSimulatorBuildCmd(SimulatorsCmd); err != nil {
		return err
	}

	parent.AddCommand(SimulatorsCmd)
	return nil
}
