// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/continuous-labs-ai/cli/internal/sdk/sdkinternal/utils"
	"time"
)

type AdvanceTimeRequest struct {
	// Absolute target time in RFC 3339, with at most millisecond precision.
	To time.Time `json:"to"`
}

func (a AdvanceTimeRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AdvanceTimeRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AdvanceTimeRequest) GetTo() time.Time {
	if a == nil {
		return time.Time{}
	}
	return a.To
}
