// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/continuous-labs-ai/cli/internal/sdk/sdkinternal/utils"
)

// BuildSimulatorRequestModel - Model that builds and reviews the Simulator. Defaults to gpt-6-astra. Its provider is derived from the model.
type BuildSimulatorRequestModel string

const (
	BuildSimulatorRequestModelGpt6Astra     BuildSimulatorRequestModel = "gpt-6-astra"
	BuildSimulatorRequestModelGpt6Sol       BuildSimulatorRequestModel = "gpt-6-sol"
	BuildSimulatorRequestModelClaudeOpus55  BuildSimulatorRequestModel = "claude-opus-5-5"
	BuildSimulatorRequestModelClaudeFable51 BuildSimulatorRequestModel = "claude-fable-5-1"
)

func (e BuildSimulatorRequestModel) ToPointer() *BuildSimulatorRequestModel {
	return &e
}
func (e *BuildSimulatorRequestModel) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "gpt-6-astra":
		fallthrough
	case "gpt-6-sol":
		fallthrough
	case "claude-opus-5-5":
		fallthrough
	case "claude-fable-5-1":
		*e = BuildSimulatorRequestModel(v)
		return nil
	default:
		return fmt.Errorf("invalid value for BuildSimulatorRequestModel: %v", v)
	}
}

// BuildSimulatorRequestSpecKind - Source specification format. Omission detects the format.
type BuildSimulatorRequestSpecKind string

const (
	BuildSimulatorRequestSpecKindOpenapi BuildSimulatorRequestSpecKind = "openapi"
	BuildSimulatorRequestSpecKindWsdl    BuildSimulatorRequestSpecKind = "wsdl"
)

func (e BuildSimulatorRequestSpecKind) ToPointer() *BuildSimulatorRequestSpecKind {
	return &e
}
func (e *BuildSimulatorRequestSpecKind) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "openapi":
		fallthrough
	case "wsdl":
		*e = BuildSimulatorRequestSpecKind(v)
		return nil
	default:
		return fmt.Errorf("invalid value for BuildSimulatorRequestSpecKind: %v", v)
	}
}

type BuildSimulatorRequest struct {
	// Regular expressions (RE2 syntax) that select the operations to implement. Each is matched against the OpenAPI operationId or the WSDL operation name; an operation is kept when any expression matches, and an OpenAPI operation without an operationId is dropped. At most 64 expressions of at most 1,024 characters each. Omit or send an empty list to keep every operation. Not allowed for an incremental build.
	Filter []string `json:"filter,omitzero"`
	// Instructions for the builder. Required for an incremental build. At most 16,384 characters and 65,536 UTF-8 bytes; must not be blank or contain U+0000.
	Instructions *string `json:"instructions,omitzero"`
	// Model that builds and reviews the Simulator. Defaults to gpt-6-astra. Its provider is derived from the model.
	Model *BuildSimulatorRequestModel `default:"gpt-6-astra" json:"model"`
	// Name for the Simulator. Omission generates a name. Names must not contain U+0000. The ID stays its identity, and names need not be unique.
	Name *string `json:"name,omitzero"`
	// Parent Simulator ID. With instructions and no spec this starts an incremental build: the parent must be ready, and the request takes no filter or spec_kind.
	ParentID *string `json:"parent_id,omitzero"`
	// Source specification format. Omission detects the format.
	SpecKind *BuildSimulatorRequestSpecKind `json:"spec_kind,omitzero"`
	// Time limit for generation and validation in seconds, from 1 to 72000. Defaults to 14400 (four hours). Excludes queue wait and finalization. Retries share the same deadline.
	TimeoutSeconds *int64 `default:"14400" json:"timeout_seconds"`
}

func (b BuildSimulatorRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(b, "", false)
}

func (b *BuildSimulatorRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &b, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (b *BuildSimulatorRequest) GetFilter() []string {
	if b == nil {
		return nil
	}
	return b.Filter
}

func (b *BuildSimulatorRequest) GetInstructions() *string {
	if b == nil {
		return nil
	}
	return b.Instructions
}

func (b *BuildSimulatorRequest) GetModel() *BuildSimulatorRequestModel {
	if b == nil {
		return nil
	}
	return b.Model
}

func (b *BuildSimulatorRequest) GetName() *string {
	if b == nil {
		return nil
	}
	return b.Name
}

func (b *BuildSimulatorRequest) GetParentID() *string {
	if b == nil {
		return nil
	}
	return b.ParentID
}

func (b *BuildSimulatorRequest) GetSpecKind() *BuildSimulatorRequestSpecKind {
	if b == nil {
		return nil
	}
	return b.SpecKind
}

func (b *BuildSimulatorRequest) GetTimeoutSeconds() *int64 {
	if b == nil {
		return nil
	}
	return b.TimeoutSeconds
}
