// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/continuous-labs-ai/cli/internal/sdk/sdkinternal/utils"
	"time"
)

// BuildWorldRequestBuilder - Legacy provider selection. Alone it selects the provider's default model (openai is gpt-6-astra, claude is claude-fable-5-1); with model it must name the model's provider.
type BuildWorldRequestBuilder string

const (
	BuildWorldRequestBuilderOpenai BuildWorldRequestBuilder = "openai"
	BuildWorldRequestBuilderClaude BuildWorldRequestBuilder = "claude"
)

func (e BuildWorldRequestBuilder) ToPointer() *BuildWorldRequestBuilder {
	return &e
}
func (e *BuildWorldRequestBuilder) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "openai":
		fallthrough
	case "claude":
		*e = BuildWorldRequestBuilder(v)
		return nil
	default:
		return fmt.Errorf("invalid value for BuildWorldRequestBuilder: %v", v)
	}
}

// BuildWorldRequestModel - Model that builds and reviews starting data. Defaults to gpt-6-astra. Its provider is derived from the model.
type BuildWorldRequestModel string

const (
	BuildWorldRequestModelGpt6Astra     BuildWorldRequestModel = "gpt-6-astra"
	BuildWorldRequestModelGpt6Sol       BuildWorldRequestModel = "gpt-6-sol"
	BuildWorldRequestModelClaudeOpus55  BuildWorldRequestModel = "claude-opus-5-5"
	BuildWorldRequestModelClaudeFable51 BuildWorldRequestModel = "claude-fable-5-1"
)

func (e BuildWorldRequestModel) ToPointer() *BuildWorldRequestModel {
	return &e
}
func (e *BuildWorldRequestModel) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "gpt-6-astra":
		fallthrough
	case "gpt-6-sol":
		fallthrough
	case "claude-opus-5-5":
		fallthrough
	case "claude-fable-5-1":
		*e = BuildWorldRequestModel(v)
		return nil
	default:
		return fmt.Errorf("invalid value for BuildWorldRequestModel: %v", v)
	}
}

type BuildWorldRequest struct {
	// Legacy provider selection. Alone it selects the provider's default model (openai is gpt-6-astra, claude is claude-fable-5-1); with model it must name the model's provider.
	Builder *BuildWorldRequestBuilder `json:"builder,omitzero"`
	// Describe the initial data, scenario, and relationships. Populated Worlds support up to 8 selected Simulators and 1,000 starting records in total. Named record types replace their default data. At most 16,384 characters and 65,536 UTF-8 bytes. U+0000 is not permitted.
	Instructions *string `json:"instructions,omitzero"`
	// Model that builds and reviews starting data. Defaults to gpt-6-astra. Its provider is derived from the model.
	Model *BuildWorldRequestModel `default:"gpt-6-astra" json:"model"`
	// Name for the World. Omission generates a name. The ID stays its identity, and names need not be unique.
	Name *string `json:"name,omitzero"`
	// Simulator IDs for the World.
	Simulators []string `json:"simulators"`
	// Simulated time the World starts at, in RFC 3339 format. Omission uses 2024-01-01T00:00:00Z. Saved starting data keeps its build dates.
	StartTime *time.Time `json:"start_time,omitzero"`
	// Time limit for generation and validation in seconds, from 1 to 72000. Defaults to 14400 (four hours). Excludes queue wait and finalization. Retries share the same deadline.
	TimeoutSeconds *int64 `default:"14400" json:"timeout_seconds"`
}

func (b BuildWorldRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(b, "", false)
}

func (b *BuildWorldRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &b, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (b *BuildWorldRequest) GetBuilder() *BuildWorldRequestBuilder {
	if b == nil {
		return nil
	}
	return b.Builder
}

func (b *BuildWorldRequest) GetInstructions() *string {
	if b == nil {
		return nil
	}
	return b.Instructions
}

func (b *BuildWorldRequest) GetModel() *BuildWorldRequestModel {
	if b == nil {
		return nil
	}
	return b.Model
}

func (b *BuildWorldRequest) GetName() *string {
	if b == nil {
		return nil
	}
	return b.Name
}

func (b *BuildWorldRequest) GetSimulators() []string {
	if b == nil {
		return []string{}
	}
	return b.Simulators
}

func (b *BuildWorldRequest) GetStartTime() *time.Time {
	if b == nil {
		return nil
	}
	return b.StartTime
}

func (b *BuildWorldRequest) GetTimeoutSeconds() *int64 {
	if b == nil {
		return nil
	}
	return b.TimeoutSeconds
}
