// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/continuous-labs-ai/cli/internal/sdk/sdkinternal/utils"
	"time"
)

type BuildToolCall struct {
	// Time the call ran.
	At time.Time `json:"at"`
	// Name of the tool. Arguments and output are private.
	Tool string `json:"tool"`
}

func (b BuildToolCall) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(b, "", false)
}

func (b *BuildToolCall) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &b, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (b *BuildToolCall) GetAt() time.Time {
	if b == nil {
		return time.Time{}
	}
	return b.At
}

func (b *BuildToolCall) GetTool() string {
	if b == nil {
		return ""
	}
	return b.Tool
}
