// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type BuildWorldRequest struct {
	// Instructions for the builder. At most 16,384 characters and 65,536 UTF-8 bytes; must not be blank or contain U+0000.
	Instructions *string `json:"instructions,omitzero"`
	// Simulator IDs for the World.
	Simulators []string `json:"simulators"`
}

func (b *BuildWorldRequest) GetInstructions() *string {
	if b == nil {
		return nil
	}
	return b.Instructions
}

func (b *BuildWorldRequest) GetSimulators() []string {
	if b == nil {
		return []string{}
	}
	return b.Simulators
}
