// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/continuous-labs-ai/cli/internal/sdk/sdkinternal/utils"
)

// Builder - Model provider that builds the Simulator. Defaults to claude.
type Builder string

const (
	BuilderOpenai Builder = "openai"
	BuilderClaude Builder = "claude"
)

func (e Builder) ToPointer() *Builder {
	return &e
}
func (e *Builder) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "openai":
		fallthrough
	case "claude":
		*e = Builder(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Builder: %v", v)
	}
}

// SpecKind - Source specification format. Omission detects the format.
type SpecKind string

const (
	SpecKindOpenapi SpecKind = "openapi"
	SpecKindWsdl    SpecKind = "wsdl"
)

func (e SpecKind) ToPointer() *SpecKind {
	return &e
}
func (e *SpecKind) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "openapi":
		fallthrough
	case "wsdl":
		*e = SpecKind(v)
		return nil
	default:
		return fmt.Errorf("invalid value for SpecKind: %v", v)
	}
}

type BuildSimulatorRequest struct {
	// Model provider that builds the Simulator. Defaults to claude.
	Builder *Builder `default:"claude" json:"builder"`
	// Regular expressions (RE2 syntax) that select the operations to implement. Each is matched against the OpenAPI operationId or the WSDL operation name; an operation is kept when any expression matches, and an OpenAPI operation without an operationId is dropped. At most 64 expressions of at most 1,024 characters each. Omit or send an empty list to keep every operation. Not allowed for an incremental build.
	Filter []string `json:"filter,omitzero"`
	// Instructions for the builder. Required for an incremental build. At most 16,384 characters and 65,536 UTF-8 bytes; must not be blank or contain U+0000.
	Instructions *string `json:"instructions,omitzero"`
	// Optional Simulator name. Names cannot start with smr_. Omission generates a name.
	Name *string `json:"name,omitzero"`
	// Parent Simulator ID. With instructions and no spec this starts an incremental build: the parent must be ready, and the request takes no filter or spec_kind.
	ParentID *string `json:"parent_id,omitzero"`
	// Source specification format. Omission detects the format.
	SpecKind *SpecKind `json:"spec_kind,omitzero"`
}

func (b BuildSimulatorRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(b, "", false)
}

func (b *BuildSimulatorRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &b, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (b *BuildSimulatorRequest) GetBuilder() *Builder {
	if b == nil {
		return nil
	}
	return b.Builder
}

func (b *BuildSimulatorRequest) GetFilter() []string {
	if b == nil {
		return nil
	}
	return b.Filter
}

func (b *BuildSimulatorRequest) GetInstructions() *string {
	if b == nil {
		return nil
	}
	return b.Instructions
}

func (b *BuildSimulatorRequest) GetName() *string {
	if b == nil {
		return nil
	}
	return b.Name
}

func (b *BuildSimulatorRequest) GetParentID() *string {
	if b == nil {
		return nil
	}
	return b.ParentID
}

func (b *BuildSimulatorRequest) GetSpecKind() *SpecKind {
	if b == nil {
		return nil
	}
	return b.SpecKind
}
