// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/continuous-labs-ai/cli/internal/sdk/sdkinternal/utils"
	"time"
)

// ClockAdvanceStatus - Durable operation state. Poll while pending or running.
type ClockAdvanceStatus string

const (
	ClockAdvanceStatusPending   ClockAdvanceStatus = "pending"
	ClockAdvanceStatusRunning   ClockAdvanceStatus = "running"
	ClockAdvanceStatusCompleted ClockAdvanceStatus = "completed"
	ClockAdvanceStatusFailed    ClockAdvanceStatus = "failed"
)

func (e ClockAdvanceStatus) ToPointer() *ClockAdvanceStatus {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *ClockAdvanceStatus) IsExact() bool {
	if e != nil {
		switch *e {
		case "pending", "running", "completed", "failed":
			return true
		}
	}
	return false
}

type ClockAdvance struct {
	Error *ResourceError `json:"error"`
	// Number of committed event executions.
	EventCount int64 `json:"event_count"`
	// Clock before the requested advance.
	From time.Time `json:"from"`
	// Stable clock advance operation ID.
	ID string `json:"id"`
	// Progress for each participating Simulation.
	Members []ClockAdvanceMember `json:"members"`
	// Durable operation state. Poll while pending or running.
	Status ClockAdvanceStatus `json:"status"`
	// Committed local step, or null for no change or a World operation.
	Step *int64 `json:"step"`
	// Requested absolute target time.
	To time.Time `json:"to"`
}

func (c ClockAdvance) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ClockAdvance) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *ClockAdvance) GetError() *ResourceError {
	if c == nil {
		return nil
	}
	return c.Error
}

func (c *ClockAdvance) GetEventCount() int64 {
	if c == nil {
		return 0
	}
	return c.EventCount
}

func (c *ClockAdvance) GetFrom() time.Time {
	if c == nil {
		return time.Time{}
	}
	return c.From
}

func (c *ClockAdvance) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}

func (c *ClockAdvance) GetMembers() []ClockAdvanceMember {
	if c == nil {
		return []ClockAdvanceMember{}
	}
	return c.Members
}

func (c *ClockAdvance) GetStatus() ClockAdvanceStatus {
	if c == nil {
		return ClockAdvanceStatus("")
	}
	return c.Status
}

func (c *ClockAdvance) GetStep() *int64 {
	if c == nil {
		return nil
	}
	return c.Step
}

func (c *ClockAdvance) GetTo() time.Time {
	if c == nil {
		return time.Time{}
	}
	return c.To
}
