// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// ClockAdvanceMemberStatus - Whether this member is pending, committed, failed, or skipped because it is not running.
type ClockAdvanceMemberStatus string

const (
	ClockAdvanceMemberStatusPending   ClockAdvanceMemberStatus = "pending"
	ClockAdvanceMemberStatusCompleted ClockAdvanceMemberStatus = "completed"
	ClockAdvanceMemberStatusFailed    ClockAdvanceMemberStatus = "failed"
	ClockAdvanceMemberStatusSkipped   ClockAdvanceMemberStatus = "skipped"
)

func (e ClockAdvanceMemberStatus) ToPointer() *ClockAdvanceMemberStatus {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *ClockAdvanceMemberStatus) IsExact() bool {
	if e != nil {
		switch *e {
		case "pending", "completed", "failed", "skipped":
			return true
		}
	}
	return false
}

type ClockAdvanceMember struct {
	Error *ResourceError `json:"error"`
	// Number of committed event executions.
	EventCount int64 `json:"event_count"`
	// Member Simulation ID.
	SimulationID string `json:"simulation_id"`
	// Whether this member is pending, committed, failed, or skipped because it is not running.
	Status ClockAdvanceMemberStatus `json:"status"`
	// Committed local step, or null for no change or a failed advance.
	Step *int64 `json:"step"`
}

func (c *ClockAdvanceMember) GetError() *ResourceError {
	if c == nil {
		return nil
	}
	return c.Error
}

func (c *ClockAdvanceMember) GetEventCount() int64 {
	if c == nil {
		return 0
	}
	return c.EventCount
}

func (c *ClockAdvanceMember) GetSimulationID() string {
	if c == nil {
		return ""
	}
	return c.SimulationID
}

func (c *ClockAdvanceMember) GetStatus() ClockAdvanceMemberStatus {
	if c == nil {
		return ClockAdvanceMemberStatus("")
	}
	return c.Status
}

func (c *ClockAdvanceMember) GetStep() *int64 {
	if c == nil {
		return nil
	}
	return c.Step
}
