// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/continuous-labs-ai/cli/internal/sdk/sdkinternal/utils"
	"time"
)

// ClockAdvanceMemberStatus - Whether this member is pending, committed, failed, or skipped because it is not running.
type ClockAdvanceMemberStatus string

const (
	ClockAdvanceMemberStatusPending   ClockAdvanceMemberStatus = "pending"
	ClockAdvanceMemberStatusCompleted ClockAdvanceMemberStatus = "completed"
	ClockAdvanceMemberStatusFailed    ClockAdvanceMemberStatus = "failed"
	ClockAdvanceMemberStatusSkipped   ClockAdvanceMemberStatus = "skipped"
)

func (e ClockAdvanceMemberStatus) ToPointer() *ClockAdvanceMemberStatus {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *ClockAdvanceMemberStatus) IsExact() bool {
	if e != nil {
		switch *e {
		case "pending", "completed", "failed", "skipped":
			return true
		}
	}
	return false
}

type ClockAdvanceMember struct {
	Error *ResourceError `json:"error"`
	// Number of committed event executions.
	EventCount int64 `json:"event_count"`
	// Clock time a failed advance reached with the batches it kept committed.
	Reached *time.Time `json:"reached,omitzero"`
	// Member Simulation ID.
	SimulationID string `json:"simulation_id"`
	// Whether this member is pending, committed, failed, or skipped because it is not running.
	Status ClockAdvanceMemberStatus `json:"status"`
	// Last committed local step, or null when the advance committed none.
	Step *int64 `json:"step"`
}

func (c ClockAdvanceMember) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ClockAdvanceMember) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *ClockAdvanceMember) GetError() *ResourceError {
	if c == nil {
		return nil
	}
	return c.Error
}

func (c *ClockAdvanceMember) GetEventCount() int64 {
	if c == nil {
		return 0
	}
	return c.EventCount
}

func (c *ClockAdvanceMember) GetReached() *time.Time {
	if c == nil {
		return nil
	}
	return c.Reached
}

func (c *ClockAdvanceMember) GetSimulationID() string {
	if c == nil {
		return ""
	}
	return c.SimulationID
}

func (c *ClockAdvanceMember) GetStatus() ClockAdvanceMemberStatus {
	if c == nil {
		return ClockAdvanceMemberStatus("")
	}
	return c.Status
}

func (c *ClockAdvanceMember) GetStep() *int64 {
	if c == nil {
		return nil
	}
	return c.Step
}
