// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type CloneSimulatorResponse struct {
	// OCI manifest digest, unchanged from the source.
	Digest string `json:"digest"`
	// New Simulator ID in the target workspace, or the same ID on an idempotent retry.
	ID string `json:"id"`
	// Display name of the clone.
	Name string `json:"name"`
	// Target workspace.
	WorkspaceID string `json:"workspace_id"`
}

func (c *CloneSimulatorResponse) GetDigest() string {
	if c == nil {
		return ""
	}
	return c.Digest
}

func (c *CloneSimulatorResponse) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}

func (c *CloneSimulatorResponse) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}

func (c *CloneSimulatorResponse) GetWorkspaceID() string {
	if c == nil {
		return ""
	}
	return c.WorkspaceID
}
