// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type CreateSimulationRequest struct {
	// Optional Simulation name. Omission generates a name.
	Name *string `json:"name,omitzero"`
	// ID of the ready Simulator.
	SimulatorID string `json:"simulator_id"`
}

func (c *CreateSimulationRequest) GetName() *string {
	if c == nil {
		return nil
	}
	return c.Name
}

func (c *CreateSimulationRequest) GetSimulatorID() string {
	if c == nil {
		return ""
	}
	return c.SimulatorID
}
