// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/continuous-labs-ai/cli/internal/sdk/sdkinternal/utils"
)

type CreateCredentialRequest struct {
	// The https URL of the real system. Requests go to paths under it.
	BaseURL string `json:"base_url"`
	// The HTTP header that carries the value.
	Header *string `default:"Authorization" json:"header"`
	// Credential name.
	Name string `json:"name"`
	// The full header value, for example Bearer followed by a token. The API never returns it.
	Value string `json:"value"`
}

func (c CreateCredentialRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateCredentialRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateCredentialRequest) GetBaseURL() string {
	if c == nil {
		return ""
	}
	return c.BaseURL
}

func (c *CreateCredentialRequest) GetHeader() *string {
	if c == nil {
		return nil
	}
	return c.Header
}

func (c *CreateCredentialRequest) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}

func (c *CreateCredentialRequest) GetValue() string {
	if c == nil {
		return ""
	}
	return c.Value
}
