// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/continuous-labs-ai/cli/internal/sdk/sdkinternal/utils"
	"time"
)

// CreatedSimulationStatus - Current status. running serves requests. paused means the Simulation was idle and the platform paused it; the next request wakes it. stopped means its state is saved and requests return 409 until you start it.
type CreatedSimulationStatus string

const (
	CreatedSimulationStatusRunning CreatedSimulationStatus = "running"
	CreatedSimulationStatusPaused  CreatedSimulationStatus = "paused"
	CreatedSimulationStatusStopped CreatedSimulationStatus = "stopped"
)

func (e CreatedSimulationStatus) ToPointer() *CreatedSimulationStatus {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *CreatedSimulationStatus) IsExact() bool {
	if e != nil {
		switch *e {
		case "running", "paused", "stopped":
			return true
		}
	}
	return false
}

type CreatedSimulation struct {
	// Simulation creation time.
	CreatedAt time.Time `json:"created_at"`
	// Base URL for requests to the Simulation.
	Endpoint string `json:"endpoint"`
	// Token expiration time.
	ExpiresAt time.Time `json:"expires_at"`
	// Simulation ID.
	ID string `json:"id"`
	// Simulation name.
	Name string `json:"name"`
	// Source Simulation ID for a fork, or null.
	ParentID *string `json:"parent_id"`
	// ID of the Simulator.
	SimulatorID string `json:"simulator_id"`
	// Current status. running serves requests. paused means the Simulation was idle and the platform paused it; the next request wakes it. stopped means its state is saved and requests return 409 until you start it.
	Status CreatedSimulationStatus `json:"status"`
	// Token for requests to the Simulation endpoint. Send it in the X-Continuous-Simulation-Token header. It is returned only here; list and get omit it. Create more with POST /v1/simulations/{id}/tokens.
	Token string `json:"token"`
}

func (c CreatedSimulation) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreatedSimulation) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreatedSimulation) GetCreatedAt() time.Time {
	if c == nil {
		return time.Time{}
	}
	return c.CreatedAt
}

func (c *CreatedSimulation) GetEndpoint() string {
	if c == nil {
		return ""
	}
	return c.Endpoint
}

func (c *CreatedSimulation) GetExpiresAt() time.Time {
	if c == nil {
		return time.Time{}
	}
	return c.ExpiresAt
}

func (c *CreatedSimulation) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}

func (c *CreatedSimulation) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}

func (c *CreatedSimulation) GetParentID() *string {
	if c == nil {
		return nil
	}
	return c.ParentID
}

func (c *CreatedSimulation) GetSimulatorID() string {
	if c == nil {
		return ""
	}
	return c.SimulatorID
}

func (c *CreatedSimulation) GetStatus() CreatedSimulationStatus {
	if c == nil {
		return CreatedSimulationStatus("")
	}
	return c.Status
}

func (c *CreatedSimulation) GetToken() string {
	if c == nil {
		return ""
	}
	return c.Token
}
