// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/continuous-labs-ai/cli/internal/sdk/sdkinternal/utils"
	"time"
)

type Credential struct {
	// The https URL of the real system, or null for a credential created without one. A build can use only a credential with a base URL.
	BaseURL *string `json:"base_url"`
	// Credential creation time.
	CreatedAt time.Time `json:"created_at"`
	// The HTTP header that carries the value.
	Header string `json:"header"`
	// Credential ID.
	ID string `json:"id"`
	// Credential name. Names need not be unique.
	Name string `json:"name"`
}

func (c Credential) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *Credential) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *Credential) GetBaseURL() *string {
	if c == nil {
		return nil
	}
	return c.BaseURL
}

func (c *Credential) GetCreatedAt() time.Time {
	if c == nil {
		return time.Time{}
	}
	return c.CreatedAt
}

func (c *Credential) GetHeader() string {
	if c == nil {
		return ""
	}
	return c.Header
}

func (c *Credential) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}

func (c *Credential) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}
