// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/continuous-labs-ai/cli/internal/sdk/sdkinternal/utils"
	"time"
)

type CurrentSimulationToken struct {
	// Null for a lifetime credential.
	ExpiresAt *time.Time `json:"expires_at"`
	// Current Simulation endpoint credential.
	Token string `json:"token"`
}

func (c CurrentSimulationToken) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CurrentSimulationToken) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CurrentSimulationToken) GetExpiresAt() *time.Time {
	if c == nil {
		return nil
	}
	return c.ExpiresAt
}

func (c *CurrentSimulationToken) GetToken() string {
	if c == nil {
		return ""
	}
	return c.Token
}
