// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ForkSimulationRequest struct {
	// Completed step to fork from. Omission forks from the latest state.
	AtStep *int64 `json:"at_step,omitzero"`
	// Optional child Simulation name. Omission generates a name.
	Name *string `json:"name,omitzero"`
}

func (f *ForkSimulationRequest) GetAtStep() *int64 {
	if f == nil {
		return nil
	}
	return f.AtStep
}

func (f *ForkSimulationRequest) GetName() *string {
	if f == nil {
		return nil
	}
	return f.Name
}
