// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type Limitation struct {
	// The operations the limitation affects, readably, or Simulator when it names none.
	Location string `json:"location"`
	// What the Simulator does differently from the real system.
	Message string `json:"message"`
	// Operation IDs the limitation affects, or empty when it names none.
	Operations []string `json:"operations"`
	// Whether review confirmed that the pinned contract or the scaffold cannot express the correct behavior. False for a limitation the build recorded after review or that review did not confirm.
	Reviewed bool `json:"reviewed"`
}

func (l *Limitation) GetLocation() string {
	if l == nil {
		return ""
	}
	return l.Location
}

func (l *Limitation) GetMessage() string {
	if l == nil {
		return ""
	}
	return l.Message
}

func (l *Limitation) GetOperations() []string {
	if l == nil {
		return []string{}
	}
	return l.Operations
}

func (l *Limitation) GetReviewed() bool {
	if l == nil {
		return false
	}
	return l.Reviewed
}
