// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ListSimulationStepsResponse struct {
	// Cursor for the next page, or null.
	NextCursor *string `json:"next_cursor"`
	// Recorded steps in this page.
	Steps []Step `json:"steps"`
}

func (l *ListSimulationStepsResponse) GetNextCursor() *string {
	if l == nil {
		return nil
	}
	return l.NextCursor
}

func (l *ListSimulationStepsResponse) GetSteps() []Step {
	if l == nil {
		return []Step{}
	}
	return l.Steps
}
