// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ListSimulationsResponse struct {
	// Cursor for the next page, or null.
	NextCursor *string `json:"next_cursor"`
	// Simulations in this page.
	Simulations []Simulation `json:"simulations"`
}

func (l *ListSimulationsResponse) GetNextCursor() *string {
	if l == nil {
		return nil
	}
	return l.NextCursor
}

func (l *ListSimulationsResponse) GetSimulations() []Simulation {
	if l == nil {
		return []Simulation{}
	}
	return l.Simulations
}
