// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ListSimulatorsResponse struct {
	// Cursor for the next page, or null.
	NextCursor *string `json:"next_cursor"`
	// Simulators in this page.
	Simulators []Simulator `json:"simulators"`
}

func (l *ListSimulatorsResponse) GetNextCursor() *string {
	if l == nil {
		return nil
	}
	return l.NextCursor
}

func (l *ListSimulatorsResponse) GetSimulators() []Simulator {
	if l == nil {
		return []Simulator{}
	}
	return l.Simulators
}
