// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ListWorldsResponse struct {
	// Cursor for the next page, or null when this is the last page.
	NextCursor *string `json:"next_cursor"`
	// Worlds in this page.
	Worlds []World `json:"worlds"`
}

func (l *ListWorldsResponse) GetNextCursor() *string {
	if l == nil {
		return nil
	}
	return l.NextCursor
}

func (l *ListWorldsResponse) GetWorlds() []World {
	if l == nil {
		return []World{}
	}
	return l.Worlds
}
