// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ListCredentialsResponse struct {
	// Credential metadata in this page, newest first.
	Credentials []Credential `json:"credentials"`
	// Cursor for the next page, or null.
	NextCursor *string `json:"next_cursor"`
}

func (l *ListCredentialsResponse) GetCredentials() []Credential {
	if l == nil {
		return []Credential{}
	}
	return l.Credentials
}

func (l *ListCredentialsResponse) GetNextCursor() *string {
	if l == nil {
		return nil
	}
	return l.NextCursor
}
