// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ListAdvanceEventsOutputBody struct {
	// Committed events in execution order.
	Events []ClockEvent `json:"events"`
	// Cursor for the next page, or null.
	NextCursor *string `json:"next_cursor"`
}

func (l *ListAdvanceEventsOutputBody) GetEvents() []ClockEvent {
	if l == nil {
		return []ClockEvent{}
	}
	return l.Events
}

func (l *ListAdvanceEventsOutputBody) GetNextCursor() *string {
	if l == nil {
		return nil
	}
	return l.NextCursor
}
