// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type MintSimulationTokenRequest struct {
	// Token lifetime in seconds, from 60 through 86,400.
	TTLSeconds int64 `json:"ttl_seconds"`
}

func (m *MintSimulationTokenRequest) GetTTLSeconds() int64 {
	if m == nil {
		return 0
	}
	return m.TTLSeconds
}
