// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ResourceError struct {
	// Stable machine-readable error code.
	Code string `json:"code"`
	// Safe human-readable error detail.
	Detail string `json:"detail"`
}

func (r *ResourceError) GetCode() string {
	if r == nil {
		return ""
	}
	return r.Code
}

func (r *ResourceError) GetDetail() string {
	if r == nil {
		return ""
	}
	return r.Detail
}
