// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/continuous-labs-ai/cli/internal/sdk/sdkinternal/utils"
	"time"
)

// SimulatorBuildProgressBuilder - The coding-loop provider.
type SimulatorBuildProgressBuilder string

const (
	SimulatorBuildProgressBuilderClaude SimulatorBuildProgressBuilder = "claude"
	SimulatorBuildProgressBuilderOpenai SimulatorBuildProgressBuilder = "openai"
)

func (e SimulatorBuildProgressBuilder) ToPointer() *SimulatorBuildProgressBuilder {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *SimulatorBuildProgressBuilder) IsExact() bool {
	if e != nil {
		switch *e {
		case "claude", "openai":
			return true
		}
	}
	return false
}

// SimulatorBuildProgressLastSubmission - Outcome of the most recent submit attempt, or null.
type SimulatorBuildProgressLastSubmission string

const (
	SimulatorBuildProgressLastSubmissionAccepted SimulatorBuildProgressLastSubmission = "accepted"
	SimulatorBuildProgressLastSubmissionRejected SimulatorBuildProgressLastSubmission = "rejected"
)

func (e SimulatorBuildProgressLastSubmission) ToPointer() *SimulatorBuildProgressLastSubmission {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *SimulatorBuildProgressLastSubmission) IsExact() bool {
	if e != nil {
		switch *e {
		case "accepted", "rejected":
			return true
		}
	}
	return false
}

// SimulatorBuildProgressStage - derive while the effective spec, build skeleton, and sandbox are prepared; build while the coding loop runs; assemble while an accepted artifact publishes.
type SimulatorBuildProgressStage string

const (
	SimulatorBuildProgressStageDerive   SimulatorBuildProgressStage = "derive"
	SimulatorBuildProgressStageBuild    SimulatorBuildProgressStage = "build"
	SimulatorBuildProgressStageAssemble SimulatorBuildProgressStage = "assemble"
)

func (e SimulatorBuildProgressStage) ToPointer() *SimulatorBuildProgressStage {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *SimulatorBuildProgressStage) IsExact() bool {
	if e != nil {
		switch *e {
		case "derive", "build", "assemble":
			return true
		}
	}
	return false
}

type SimulatorBuildProgress struct {
	// The coding-loop provider.
	Builder SimulatorBuildProgressBuilder `json:"builder"`
	// Outcome of the most recent submit attempt, or null.
	LastSubmission *SimulatorBuildProgressLastSubmission `json:"last_submission"`
	// Name of the most recent tool call, or null.
	LastTool *string `json:"last_tool"`
	// derive while the effective spec, build skeleton, and sandbox are prepared; build while the coding loop runs; assemble while an accepted artifact publishes.
	Stage SimulatorBuildProgressStage `json:"stage"`
	// Submit attempts.
	Submissions int64 `json:"submissions"`
	// Tool calls the coding loop executed.
	ToolCalls int64 `json:"tool_calls"`
	// Time of the last progress report.
	UpdatedAt time.Time `json:"updated_at"`
}

func (s SimulatorBuildProgress) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SimulatorBuildProgress) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *SimulatorBuildProgress) GetBuilder() SimulatorBuildProgressBuilder {
	if s == nil {
		return SimulatorBuildProgressBuilder("")
	}
	return s.Builder
}

func (s *SimulatorBuildProgress) GetLastSubmission() *SimulatorBuildProgressLastSubmission {
	if s == nil {
		return nil
	}
	return s.LastSubmission
}

func (s *SimulatorBuildProgress) GetLastTool() *string {
	if s == nil {
		return nil
	}
	return s.LastTool
}

func (s *SimulatorBuildProgress) GetStage() SimulatorBuildProgressStage {
	if s == nil {
		return SimulatorBuildProgressStage("")
	}
	return s.Stage
}

func (s *SimulatorBuildProgress) GetSubmissions() int64 {
	if s == nil {
		return 0
	}
	return s.Submissions
}

func (s *SimulatorBuildProgress) GetToolCalls() int64 {
	if s == nil {
		return 0
	}
	return s.ToolCalls
}

func (s *SimulatorBuildProgress) GetUpdatedAt() time.Time {
	if s == nil {
		return time.Time{}
	}
	return s.UpdatedAt
}
