// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type SimulatorActor struct {
	// Whether a request without the header acts as this caller.
	Default bool `json:"default"`
	// The entity whose row the id keys.
	Entity string `json:"entity"`
	// The value to send in the X-Continuous-Actor header: the key of the identity row the caller acts as.
	ID string `json:"id"`
	// The build's name for the caller.
	Name string `json:"name"`
	// The caller's role in the simulated service.
	Role string `json:"role"`
}

func (s *SimulatorActor) GetDefault() bool {
	if s == nil {
		return false
	}
	return s.Default
}

func (s *SimulatorActor) GetEntity() string {
	if s == nil {
		return ""
	}
	return s.Entity
}

func (s *SimulatorActor) GetID() string {
	if s == nil {
		return ""
	}
	return s.ID
}

func (s *SimulatorActor) GetName() string {
	if s == nil {
		return ""
	}
	return s.Name
}

func (s *SimulatorActor) GetRole() string {
	if s == nil {
		return ""
	}
	return s.Role
}
