// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/continuous-labs-ai/cli/internal/sdk/sdkinternal/utils"
	"time"
)

// SimulationDetailStatus - Current status. running serves requests. paused means the Simulation was idle and the platform paused it; the next request wakes it. stopped means its state is saved and requests return 409 until you start it.
type SimulationDetailStatus string

const (
	SimulationDetailStatusRunning SimulationDetailStatus = "running"
	SimulationDetailStatusPaused  SimulationDetailStatus = "paused"
	SimulationDetailStatusStopped SimulationDetailStatus = "stopped"
)

func (e SimulationDetailStatus) ToPointer() *SimulationDetailStatus {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *SimulationDetailStatus) IsExact() bool {
	if e != nil {
		switch *e {
		case "running", "paused", "stopped":
			return true
		}
	}
	return false
}

type SimulationDetail struct {
	// Current clock advance operation ID, or null.
	ActiveAdvanceID *string `json:"active_advance_id"`
	// The callers a request can act as by sending an actor's id in the X-Continuous-Actor header. Without the header, a request acts as the default actor. Lists the actors the seed holds, plus actors only the sample holds when the Simulation includes sample data. Empty when the Simulator's build names none or its artifact cannot be read now.
	Actors []SimulatorActor `json:"actors"`
	// Simulation creation time.
	CreatedAt time.Time `json:"created_at"`
	// Current simulated time.
	CurrentTime time.Time `json:"current_time"`
	// Base URL for requests to the Simulation.
	Endpoint string `json:"endpoint"`
	// Simulation ID.
	ID string `json:"id"`
	// Whether the Simulation started with the Simulator's sample data. A fork inherits its source's state and reports false.
	IncludeSampleData bool `json:"include_sample_data"`
	// Customer JSON metadata, or null.
	Metadata any `json:"metadata"`
	// Simulation name. The ID is its identity, and names need not be unique.
	Name string `json:"name"`
	// Source Simulation ID for a fork, or null.
	ParentID *string `json:"parent_id"`
	// OCI manifest digest pinned when the Simulation was created.
	SimulatorDigest string `json:"simulator_digest"`
	// ID of the Simulator bound to this Simulation.
	SimulatorID string `json:"simulator_id"`
	// Initial simulated time.
	StartTime time.Time `json:"start_time"`
	// Current status. running serves requests. paused means the Simulation was idle and the platform paused it; the next request wakes it. stopped means its state is saved and requests return 409 until you start it.
	Status SimulationDetailStatus `json:"status"`
	// ID of the World that owns this Simulation, or null.
	WorldID *string `json:"world_id"`
}

func (s SimulationDetail) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SimulationDetail) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *SimulationDetail) GetActiveAdvanceID() *string {
	if s == nil {
		return nil
	}
	return s.ActiveAdvanceID
}

func (s *SimulationDetail) GetActors() []SimulatorActor {
	if s == nil {
		return []SimulatorActor{}
	}
	return s.Actors
}

func (s *SimulationDetail) GetCreatedAt() time.Time {
	if s == nil {
		return time.Time{}
	}
	return s.CreatedAt
}

func (s *SimulationDetail) GetCurrentTime() time.Time {
	if s == nil {
		return time.Time{}
	}
	return s.CurrentTime
}

func (s *SimulationDetail) GetEndpoint() string {
	if s == nil {
		return ""
	}
	return s.Endpoint
}

func (s *SimulationDetail) GetID() string {
	if s == nil {
		return ""
	}
	return s.ID
}

func (s *SimulationDetail) GetIncludeSampleData() bool {
	if s == nil {
		return false
	}
	return s.IncludeSampleData
}

func (s *SimulationDetail) GetMetadata() any {
	if s == nil {
		return nil
	}
	return s.Metadata
}

func (s *SimulationDetail) GetName() string {
	if s == nil {
		return ""
	}
	return s.Name
}

func (s *SimulationDetail) GetParentID() *string {
	if s == nil {
		return nil
	}
	return s.ParentID
}

func (s *SimulationDetail) GetSimulatorDigest() string {
	if s == nil {
		return ""
	}
	return s.SimulatorDigest
}

func (s *SimulationDetail) GetSimulatorID() string {
	if s == nil {
		return ""
	}
	return s.SimulatorID
}

func (s *SimulationDetail) GetStartTime() time.Time {
	if s == nil {
		return time.Time{}
	}
	return s.StartTime
}

func (s *SimulationDetail) GetStatus() SimulationDetailStatus {
	if s == nil {
		return SimulationDetailStatus("")
	}
	return s.Status
}

func (s *SimulationDetail) GetWorldID() *string {
	if s == nil {
		return nil
	}
	return s.WorldID
}
