// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/continuous-labs-ai/cli/internal/sdk/sdkinternal/utils"
	"time"
)

type SimulationToken struct {
	// Token expiration time.
	ExpiresAt time.Time `json:"expires_at"`
	// New token for requests to the Simulation endpoint. Send it in the X-Continuous-Simulation-Token header.
	Token string `json:"token"`
}

func (s SimulationToken) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SimulationToken) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *SimulationToken) GetExpiresAt() time.Time {
	if s == nil {
		return time.Time{}
	}
	return s.ExpiresAt
}

func (s *SimulationToken) GetToken() string {
	if s == nil {
		return ""
	}
	return s.Token
}
