// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/continuous-labs-ai/cli/internal/sdk/sdkinternal/utils"
	"time"
)

// SimulationStatus - Current Simulation status.
type SimulationStatus string

const (
	SimulationStatusRunning SimulationStatus = "running"
	SimulationStatusPaused  SimulationStatus = "paused"
	SimulationStatusStopped SimulationStatus = "stopped"
)

func (e SimulationStatus) ToPointer() *SimulationStatus {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *SimulationStatus) IsExact() bool {
	if e != nil {
		switch *e {
		case "running", "paused", "stopped":
			return true
		}
	}
	return false
}

type Simulation struct {
	// Simulation creation time.
	CreatedAt time.Time `json:"created_at"`
	// Data-plane endpoint for the Simulation.
	Endpoint string `json:"endpoint"`
	// Stable Simulation ID.
	ID string `json:"id"`
	// Simulation name.
	Name string `json:"name"`
	// Stable source Simulation ID for a fork, or null.
	ParentID *string `json:"parent_id"`
	// Stable ID of the Simulator.
	SimulatorID string `json:"simulator_id"`
	// Current Simulation status.
	Status SimulationStatus `json:"status"`
}

func (s Simulation) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *Simulation) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *Simulation) GetCreatedAt() time.Time {
	if s == nil {
		return time.Time{}
	}
	return s.CreatedAt
}

func (s *Simulation) GetEndpoint() string {
	if s == nil {
		return ""
	}
	return s.Endpoint
}

func (s *Simulation) GetID() string {
	if s == nil {
		return ""
	}
	return s.ID
}

func (s *Simulation) GetName() string {
	if s == nil {
		return ""
	}
	return s.Name
}

func (s *Simulation) GetParentID() *string {
	if s == nil {
		return nil
	}
	return s.ParentID
}

func (s *Simulation) GetSimulatorID() string {
	if s == nil {
		return ""
	}
	return s.SimulatorID
}

func (s *Simulation) GetStatus() SimulationStatus {
	if s == nil {
		return SimulationStatus("")
	}
	return s.Status
}
