// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/continuous-labs-ai/continuous-simulation-cli/internal/sdk/sdkinternal/utils"
	"time"
)

// Source - Simulator source.
type Source string

const (
	SourceWorkspace Source = "workspace"
	SourceCatalog   Source = "catalog"
)

func (e Source) ToPointer() *Source {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *Source) IsExact() bool {
	if e != nil {
		switch *e {
		case "workspace", "catalog":
			return true
		}
	}
	return false
}

// SimulatorStatus - Current build status.
type SimulatorStatus string

const (
	SimulatorStatusBuilding SimulatorStatus = "building"
	SimulatorStatusReady    SimulatorStatus = "ready"
	SimulatorStatusFailed   SimulatorStatus = "failed"
	SimulatorStatusCanceled SimulatorStatus = "canceled"
)

func (e SimulatorStatus) ToPointer() *SimulatorStatus {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *SimulatorStatus) IsExact() bool {
	if e != nil {
		switch *e {
		case "building", "ready", "failed", "canceled":
			return true
		}
	}
	return false
}

type Simulator struct {
	// Simulator creation time.
	CreatedAt time.Time      `json:"created_at"`
	Error     *ResourceError `json:"error"`
	// Stable Simulator ID.
	ID string `json:"id"`
	// Simulator name. Names cannot start with smr_.
	Name string `json:"name"`
	// Stable parent Simulator ID, or null.
	ParentID *string `json:"parent_id"`
	// Simulator source.
	Source Source `json:"source"`
	// Current build status.
	Status SimulatorStatus `json:"status"`
}

func (s Simulator) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *Simulator) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *Simulator) GetCreatedAt() time.Time {
	if s == nil {
		return time.Time{}
	}
	return s.CreatedAt
}

func (s *Simulator) GetError() *ResourceError {
	if s == nil {
		return nil
	}
	return s.Error
}

func (s *Simulator) GetID() string {
	if s == nil {
		return ""
	}
	return s.ID
}

func (s *Simulator) GetName() string {
	if s == nil {
		return ""
	}
	return s.Name
}

func (s *Simulator) GetParentID() *string {
	if s == nil {
		return nil
	}
	return s.ParentID
}

func (s *Simulator) GetSource() Source {
	if s == nil {
		return Source("")
	}
	return s.Source
}

func (s *Simulator) GetStatus() SimulatorStatus {
	if s == nil {
		return SimulatorStatus("")
	}
	return s.Status
}
