// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// SimulatorErrorCode - Stable Simulator build error code.
type SimulatorErrorCode string

const (
	SimulatorErrorCodeBuildFailed    SimulatorErrorCode = "build_failed"
	SimulatorErrorCodeBuildCancelled SimulatorErrorCode = "build_cancelled"
)

func (e SimulatorErrorCode) ToPointer() *SimulatorErrorCode {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *SimulatorErrorCode) IsExact() bool {
	if e != nil {
		switch *e {
		case "build_failed", "build_cancelled":
			return true
		}
	}
	return false
}

type SimulatorError struct {
	// Stable Simulator build error code.
	Code SimulatorErrorCode `json:"code"`
	// Safe human-readable error detail.
	Detail string `json:"detail"`
}

func (s *SimulatorError) GetCode() SimulatorErrorCode {
	if s == nil {
		return SimulatorErrorCode("")
	}
	return s.Code
}

func (s *SimulatorError) GetDetail() string {
	if s == nil {
		return ""
	}
	return s.Detail
}
