// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// SpecificationIssueKind - Whether the input is invalid, unsupported, incomplete, or has no specific diagnosis.
type SpecificationIssueKind string

const (
	SpecificationIssueKindInvalid     SpecificationIssueKind = "invalid"
	SpecificationIssueKindUnsupported SpecificationIssueKind = "unsupported"
	SpecificationIssueKindIncomplete  SpecificationIssueKind = "incomplete"
	SpecificationIssueKindUnknown     SpecificationIssueKind = "unknown"
)

func (e SpecificationIssueKind) ToPointer() *SpecificationIssueKind {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *SpecificationIssueKind) IsExact() bool {
	if e != nil {
		switch *e {
		case "invalid", "unsupported", "incomplete", "unknown":
			return true
		}
	}
	return false
}

type SpecificationIssue struct {
	// Stable validation rule code.
	Code string `json:"code"`
	// Whether the input is invalid, unsupported, incomplete, or has no specific diagnosis.
	Kind SpecificationIssueKind `json:"kind"`
	// Readable endpoint or field affected by this issue.
	Location string `json:"location"`
	// What needs attention at this location.
	Message string `json:"message"`
	// Affected operation ID or method and path, when available. Empty for document-level issues.
	Operation string `json:"operation"`
	// How to correct or address the problem.
	Suggestion string `json:"suggestion"`
}

func (s *SpecificationIssue) GetCode() string {
	if s == nil {
		return ""
	}
	return s.Code
}

func (s *SpecificationIssue) GetKind() SpecificationIssueKind {
	if s == nil {
		return SpecificationIssueKind("")
	}
	return s.Kind
}

func (s *SpecificationIssue) GetLocation() string {
	if s == nil {
		return ""
	}
	return s.Location
}

func (s *SpecificationIssue) GetMessage() string {
	if s == nil {
		return ""
	}
	return s.Message
}

func (s *SpecificationIssue) GetOperation() string {
	if s == nil {
		return ""
	}
	return s.Operation
}

func (s *SpecificationIssue) GetSuggestion() string {
	if s == nil {
		return ""
	}
	return s.Suggestion
}
