// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// SpecificationWarningCode - Stable warning code.
type SpecificationWarningCode string

const (
	SpecificationWarningCodeSpecEnumDuplicate         SpecificationWarningCode = "spec.enum_duplicate"
	SpecificationWarningCodeSpecPathParameterOptional SpecificationWarningCode = "spec.path_parameter_optional"
	SpecificationWarningCodeSpecDefaultInvalid        SpecificationWarningCode = "spec.default_invalid"
	SpecificationWarningCodeSpecResponseUntyped       SpecificationWarningCode = "spec.response_untyped"
	SpecificationWarningCodeSpecSchemaLimit           SpecificationWarningCode = "spec.schema_limit"
	SpecificationWarningCodeSpecOperationUnservable   SpecificationWarningCode = "spec.operation_unservable"
	SpecificationWarningCodeSpecVersionAmbiguous      SpecificationWarningCode = "spec.version_ambiguous"
	SpecificationWarningCodeSpecExampleNull           SpecificationWarningCode = "spec.example_null"
)

func (e SpecificationWarningCode) ToPointer() *SpecificationWarningCode {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *SpecificationWarningCode) IsExact() bool {
	if e != nil {
		switch *e {
		case "spec.enum_duplicate", "spec.path_parameter_optional", "spec.default_invalid", "spec.response_untyped", "spec.schema_limit", "spec.operation_unservable", "spec.version_ambiguous", "spec.example_null":
			return true
		}
	}
	return false
}

type SpecificationWarning struct {
	// Stable warning code.
	Code SpecificationWarningCode `json:"code"`
	// Readable endpoint or field affected by this warning.
	Location string `json:"location"`
	// What the specification declares and how the build handles it.
	Message string `json:"message"`
	// Always empty.
	Operations []string `json:"operations"`
}

func (s *SpecificationWarning) GetCode() SpecificationWarningCode {
	if s == nil {
		return SpecificationWarningCode("")
	}
	return s.Code
}

func (s *SpecificationWarning) GetLocation() string {
	if s == nil {
		return ""
	}
	return s.Location
}

func (s *SpecificationWarning) GetMessage() string {
	if s == nil {
		return ""
	}
	return s.Message
}

func (s *SpecificationWarning) GetOperations() []string {
	if s == nil {
		return []string{}
	}
	return s.Operations
}
