// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type Step struct {
	// HTTP method and path of the request that produced this step, without the query string, for example POST /v1/widgets.
	Label string `json:"label"`
	// Step number. Use it as at_step when you fork.
	Step int64 `json:"step"`
}

func (s *Step) GetLabel() string {
	if s == nil {
		return ""
	}
	return s.Label
}

func (s *Step) GetStep() int64 {
	if s == nil {
		return 0
	}
	return s.Step
}
