// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/continuous-labs-ai/cli/internal/sdk/sdkinternal/utils"
	"time"
)

// StepKind - api for an API write or advance for a clock advance.
type StepKind string

const (
	StepKindAPI     StepKind = "api"
	StepKindAdvance StepKind = "advance"
)

func (e StepKind) ToPointer() *StepKind {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *StepKind) IsExact() bool {
	if e != nil {
		switch *e {
		case "api", "advance":
			return true
		}
	}
	return false
}

type Step struct {
	// Advance that produced this step, if any.
	AdvanceID *string `json:"advance_id"`
	// api for an API write or advance for a clock advance.
	Kind StepKind `json:"kind"`
	// HTTP method and path of the request that produced this step, without the query string, for example POST /v1/widgets.
	Label string `json:"label"`
	// Step number. Use it as at_step when you fork.
	Step int64 `json:"step"`
	// Clock after the step.
	TimeAfter *time.Time `json:"time_after"`
	// Clock before the step.
	TimeBefore *time.Time `json:"time_before"`
}

func (s Step) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *Step) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *Step) GetAdvanceID() *string {
	if s == nil {
		return nil
	}
	return s.AdvanceID
}

func (s *Step) GetKind() StepKind {
	if s == nil {
		return StepKind("")
	}
	return s.Kind
}

func (s *Step) GetLabel() string {
	if s == nil {
		return ""
	}
	return s.Label
}

func (s *Step) GetStep() int64 {
	if s == nil {
		return 0
	}
	return s.Step
}

func (s *Step) GetTimeAfter() *time.Time {
	if s == nil {
		return nil
	}
	return s.TimeAfter
}

func (s *Step) GetTimeBefore() *time.Time {
	if s == nil {
		return nil
	}
	return s.TimeBefore
}
