// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type UpdateCredentialRequest struct {
	// New https URL of the real system.
	BaseURL *string `json:"base_url,omitzero"`
	// New HTTP header that carries the value.
	Header *string `json:"header,omitzero"`
	// New credential name.
	Name *string `json:"name,omitzero"`
	// New full header value. Required when base_url or header changes. Builds that start an agent after the change use it. The API never returns it.
	Value *string `json:"value,omitzero"`
}

func (u *UpdateCredentialRequest) GetBaseURL() *string {
	if u == nil {
		return nil
	}
	return u.BaseURL
}

func (u *UpdateCredentialRequest) GetHeader() *string {
	if u == nil {
		return nil
	}
	return u.Header
}

func (u *UpdateCredentialRequest) GetName() *string {
	if u == nil {
		return nil
	}
	return u.Name
}

func (u *UpdateCredentialRequest) GetValue() *string {
	if u == nil {
		return nil
	}
	return u.Value
}
