// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// WorldErrorCode - Stable World error code.
type WorldErrorCode string

const (
	WorldErrorCodeWorldBuildCanceled         WorldErrorCode = "world_build_canceled"
	WorldErrorCodeWorldStartFailed           WorldErrorCode = "world_start_failed"
	WorldErrorCodeWorldCreateFailed          WorldErrorCode = "world_create_failed"
	WorldErrorCodeWorldFailed                WorldErrorCode = "world_failed"
	WorldErrorCodeWorldPopulationFailed      WorldErrorCode = "world_population_failed"
	WorldErrorCodeWorldPopulationUnsupported WorldErrorCode = "world_population_unsupported"
	WorldErrorCodeWorldPopulationInvalid     WorldErrorCode = "world_population_invalid"
	WorldErrorCodeWorldPopulationUnavailable WorldErrorCode = "world_population_unavailable"
)

func (e WorldErrorCode) ToPointer() *WorldErrorCode {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *WorldErrorCode) IsExact() bool {
	if e != nil {
		switch *e {
		case "world_build_canceled", "world_start_failed", "world_create_failed", "world_failed", "world_population_failed", "world_population_unsupported", "world_population_invalid", "world_population_unavailable":
			return true
		}
	}
	return false
}

// WorldErrorReason - Bounded failure reason for selecting recovery guidance, or null when unavailable. Older servers can omit this field.
type WorldErrorReason string

const (
	WorldErrorReasonCanceled              WorldErrorReason = "canceled"
	WorldErrorReasonSpecificationInvalid  WorldErrorReason = "specification_invalid"
	WorldErrorReasonTimeLimit             WorldErrorReason = "time_limit"
	WorldErrorReasonServiceUnavailable    WorldErrorReason = "service_unavailable"
	WorldErrorReasonBuildFailed           WorldErrorReason = "build_failed"
	WorldErrorReasonPopulationUnsupported WorldErrorReason = "population_unsupported"
	WorldErrorReasonWorldStartFailed      WorldErrorReason = "world_start_failed"
	WorldErrorReasonWorldOperationFailed  WorldErrorReason = "world_operation_failed"
)

func (e WorldErrorReason) ToPointer() *WorldErrorReason {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *WorldErrorReason) IsExact() bool {
	if e != nil {
		switch *e {
		case "canceled", "specification_invalid", "time_limit", "service_unavailable", "build_failed", "population_unsupported", "world_start_failed", "world_operation_failed":
			return true
		}
	}
	return false
}

type WorldError struct {
	// Stable World error code.
	Code WorldErrorCode `json:"code"`
	// Safe human-readable error detail.
	Detail string `json:"detail"`
	// Bounded failure reason for selecting recovery guidance, or null when unavailable. Older servers can omit this field.
	Reason *WorldErrorReason `json:"reason"`
}

func (w *WorldError) GetCode() WorldErrorCode {
	if w == nil {
		return WorldErrorCode("")
	}
	return w.Code
}

func (w *WorldError) GetDetail() string {
	if w == nil {
		return ""
	}
	return w.Detail
}

func (w *WorldError) GetReason() *WorldErrorReason {
	if w == nil {
		return nil
	}
	return w.Reason
}
