// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type WorldDataSummary struct {
	// Defaults and inferred choices used to prepare the starting data.
	Assumptions []string `json:"assumptions"`
	// Record conditions and counts computed from a complete census of served records.
	Conditions []string `json:"conditions"`
	// Observed starting record counts for each member and record type.
	Records []WorldRecordCount `json:"records"`
	// Shared relationships checked against the data and served API values.
	Relationships []string `json:"relationships"`
}

func (w *WorldDataSummary) GetAssumptions() []string {
	if w == nil {
		return []string{}
	}
	return w.Assumptions
}

func (w *WorldDataSummary) GetConditions() []string {
	if w == nil {
		return []string{}
	}
	return w.Conditions
}

func (w *WorldDataSummary) GetRecords() []WorldRecordCount {
	if w == nil {
		return []WorldRecordCount{}
	}
	return w.Records
}

func (w *WorldDataSummary) GetRelationships() []string {
	if w == nil {
		return []string{}
	}
	return w.Relationships
}
