// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/continuous-labs-ai/cli/internal/sdk/sdkinternal/utils"
)

// WorldBuildStage - Current phase of starting-data preparation.
type WorldBuildStage string

const (
	WorldBuildStagePlanning   WorldBuildStage = "planning"
	WorldBuildStageGenerating WorldBuildStage = "generating"
	WorldBuildStageValidating WorldBuildStage = "validating"
	WorldBuildStageComplete   WorldBuildStage = "complete"
)

func (e WorldBuildStage) ToPointer() *WorldBuildStage {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *WorldBuildStage) IsExact() bool {
	if e != nil {
		switch *e {
		case "planning", "generating", "validating", "complete":
			return true
		}
	}
	return false
}

type WorldBuild struct {
	// Current phase of starting-data preparation.
	Stage   WorldBuildStage   `json:"stage"`
	Summary *WorldDataSummary `json:"summary,omitzero"`
}

func (w WorldBuild) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(w, "", false)
}

func (w *WorldBuild) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &w, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (w *WorldBuild) GetStage() WorldBuildStage {
	if w == nil {
		return WorldBuildStage("")
	}
	return w.Stage
}

func (w *WorldBuild) GetSummary() *WorldDataSummary {
	if w == nil {
		return nil
	}
	return w.Summary
}
