// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/continuous-labs-ai/cli/internal/sdk/sdkinternal/utils"
)

// Stage - Current phase of starting-data preparation.
type Stage string

const (
	StagePlanning   Stage = "planning"
	StageGenerating Stage = "generating"
	StageValidating Stage = "validating"
	StageComplete   Stage = "complete"
)

func (e Stage) ToPointer() *Stage {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *Stage) IsExact() bool {
	if e != nil {
		switch *e {
		case "planning", "generating", "validating", "complete":
			return true
		}
	}
	return false
}

type WorldBuild struct {
	// Current phase of starting-data preparation.
	Stage   Stage             `json:"stage"`
	Summary *WorldDataSummary `json:"summary,omitzero"`
}

func (w WorldBuild) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(w, "", false)
}

func (w *WorldBuild) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &w, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (w *WorldBuild) GetStage() Stage {
	if w == nil {
		return Stage("")
	}
	return w.Stage
}

func (w *WorldBuild) GetSummary() *WorldDataSummary {
	if w == nil {
		return nil
	}
	return w.Summary
}
