// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// WorldBuildProgressBuilder - Selected model provider, or null for a build created before provider selection.
type WorldBuildProgressBuilder string

const (
	WorldBuildProgressBuilderOpenai WorldBuildProgressBuilder = "openai"
	WorldBuildProgressBuilderClaude WorldBuildProgressBuilder = "claude"
)

func (e WorldBuildProgressBuilder) ToPointer() *WorldBuildProgressBuilder {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *WorldBuildProgressBuilder) IsExact() bool {
	if e != nil {
		switch *e {
		case "openai", "claude":
			return true
		}
	}
	return false
}

// WorldBuildProgressLastSubmission - Outcome of the most recent plan submission, or null.
type WorldBuildProgressLastSubmission string

const (
	WorldBuildProgressLastSubmissionAccepted WorldBuildProgressLastSubmission = "accepted"
	WorldBuildProgressLastSubmissionRejected WorldBuildProgressLastSubmission = "rejected"
)

func (e WorldBuildProgressLastSubmission) ToPointer() *WorldBuildProgressLastSubmission {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *WorldBuildProgressLastSubmission) IsExact() bool {
	if e != nil {
		switch *e {
		case "accepted", "rejected":
			return true
		}
	}
	return false
}

// WorldBuildProgressStage - Current phase of starting-data preparation.
type WorldBuildProgressStage string

const (
	WorldBuildProgressStagePlanning   WorldBuildProgressStage = "planning"
	WorldBuildProgressStageGenerating WorldBuildProgressStage = "generating"
	WorldBuildProgressStageValidating WorldBuildProgressStage = "validating"
	WorldBuildProgressStageComplete   WorldBuildProgressStage = "complete"
)

func (e WorldBuildProgressStage) ToPointer() *WorldBuildProgressStage {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *WorldBuildProgressStage) IsExact() bool {
	if e != nil {
		switch *e {
		case "planning", "generating", "validating", "complete":
			return true
		}
	}
	return false
}

type WorldBuildProgress struct {
	// Selected model provider, or null for a build created before provider selection.
	Builder *WorldBuildProgressBuilder `json:"builder"`
	// Outcome of the most recent plan submission, or null.
	LastSubmission *WorldBuildProgressLastSubmission `json:"last_submission"`
	// Name of the most recent tool, or null. Tool arguments and output are private.
	LastTool *string `json:"last_tool"`
	// The most recent tool calls, oldest first, at most 20.
	RecentTools []BuildToolCall `json:"recent_tools"`
	// Current phase of starting-data preparation.
	Stage WorldBuildProgressStage `json:"stage"`
	// Number of submitted starting-data plans.
	Submissions int64 `json:"submissions"`
	// Verified starting data, or null before a completed build.
	Summary *WorldDataSummary `json:"summary"`
	// Number of agent tool calls.
	ToolCalls int64 `json:"tool_calls"`
}

func (w *WorldBuildProgress) GetBuilder() *WorldBuildProgressBuilder {
	if w == nil {
		return nil
	}
	return w.Builder
}

func (w *WorldBuildProgress) GetLastSubmission() *WorldBuildProgressLastSubmission {
	if w == nil {
		return nil
	}
	return w.LastSubmission
}

func (w *WorldBuildProgress) GetLastTool() *string {
	if w == nil {
		return nil
	}
	return w.LastTool
}

func (w *WorldBuildProgress) GetRecentTools() []BuildToolCall {
	if w == nil {
		return []BuildToolCall{}
	}
	return w.RecentTools
}

func (w *WorldBuildProgress) GetStage() WorldBuildProgressStage {
	if w == nil {
		return WorldBuildProgressStage("")
	}
	return w.Stage
}

func (w *WorldBuildProgress) GetSubmissions() int64 {
	if w == nil {
		return 0
	}
	return w.Submissions
}

func (w *WorldBuildProgress) GetSummary() *WorldDataSummary {
	if w == nil {
		return nil
	}
	return w.Summary
}

func (w *WorldBuildProgress) GetToolCalls() int64 {
	if w == nil {
		return 0
	}
	return w.ToolCalls
}
