// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/continuous-labs-ai/cli/internal/sdk/sdkinternal/utils"
	"time"
)

// WorldStatus - Current World lifecycle status.
type WorldStatus string

const (
	WorldStatusBuilding WorldStatus = "building"
	WorldStatusReady    WorldStatus = "ready"
	WorldStatusRunning  WorldStatus = "running"
	WorldStatusStopped  WorldStatus = "stopped"
	WorldStatusFailed   WorldStatus = "failed"
	WorldStatusCanceled WorldStatus = "canceled"
)

func (e WorldStatus) ToPointer() *WorldStatus {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *WorldStatus) IsExact() bool {
	if e != nil {
		switch *e {
		case "building", "ready", "running", "stopped", "failed", "canceled":
			return true
		}
	}
	return false
}

type World struct {
	// Time when the World build started.
	CreatedAt time.Time      `json:"created_at"`
	Error     *ResourceError `json:"error"`
	// Stable World ID.
	ID string `json:"id"`
	// Build guidance stored with the World.
	Instructions string `json:"instructions"`
	// Created member Simulations. This list is empty before first start.
	Simulations []WorldSimulation `json:"simulations"`
	// Stable Simulator IDs in member order.
	Simulators []string `json:"simulators"`
	// Current World lifecycle status.
	Status WorldStatus `json:"status"`
}

func (w World) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(w, "", false)
}

func (w *World) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &w, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (w *World) GetCreatedAt() time.Time {
	if w == nil {
		return time.Time{}
	}
	return w.CreatedAt
}

func (w *World) GetError() *ResourceError {
	if w == nil {
		return nil
	}
	return w.Error
}

func (w *World) GetID() string {
	if w == nil {
		return ""
	}
	return w.ID
}

func (w *World) GetInstructions() string {
	if w == nil {
		return ""
	}
	return w.Instructions
}

func (w *World) GetSimulations() []WorldSimulation {
	if w == nil {
		return []WorldSimulation{}
	}
	return w.Simulations
}

func (w *World) GetSimulators() []string {
	if w == nil {
		return []string{}
	}
	return w.Simulators
}

func (w *World) GetStatus() WorldStatus {
	if w == nil {
		return WorldStatus("")
	}
	return w.Status
}
