// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// WorldErrorCode - Stable World error code.
type WorldErrorCode string

const (
	WorldErrorCodeWorldBuildCanceled         WorldErrorCode = "world_build_canceled"
	WorldErrorCodeWorldStartFailed           WorldErrorCode = "world_start_failed"
	WorldErrorCodeWorldCreateFailed          WorldErrorCode = "world_create_failed"
	WorldErrorCodeWorldFailed                WorldErrorCode = "world_failed"
	WorldErrorCodeWorldPopulationFailed      WorldErrorCode = "world_population_failed"
	WorldErrorCodeWorldPopulationUnsupported WorldErrorCode = "world_population_unsupported"
	WorldErrorCodeWorldPopulationInvalid     WorldErrorCode = "world_population_invalid"
	WorldErrorCodeWorldPopulationUnavailable WorldErrorCode = "world_population_unavailable"
)

func (e WorldErrorCode) ToPointer() *WorldErrorCode {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *WorldErrorCode) IsExact() bool {
	if e != nil {
		switch *e {
		case "world_build_canceled", "world_start_failed", "world_create_failed", "world_failed", "world_population_failed", "world_population_unsupported", "world_population_invalid", "world_population_unavailable":
			return true
		}
	}
	return false
}

type WorldError struct {
	// Stable World error code.
	Code WorldErrorCode `json:"code"`
	// Safe human-readable error detail.
	Detail string `json:"detail"`
}

func (w *WorldError) GetCode() WorldErrorCode {
	if w == nil {
		return WorldErrorCode("")
	}
	return w.Code
}

func (w *WorldError) GetDetail() string {
	if w == nil {
		return ""
	}
	return w.Detail
}
