// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type WorldSimulation struct {
	// Stable ID of the created Simulation.
	ID string `json:"id"`
	// Stable ID of the Simulator that this Simulation runs.
	SimulatorID string `json:"simulator_id"`
}

func (w *WorldSimulation) GetID() string {
	if w == nil {
		return ""
	}
	return w.ID
}

func (w *WorldSimulation) GetSimulatorID() string {
	if w == nil {
		return ""
	}
	return w.SimulatorID
}
